/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the OrderBilling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderBilling{}

// OrderBilling struct for OrderBilling
type OrderBilling struct {
	// Street address.
	Street *string `json:"street,omitempty"`
	// City.
	City *string `json:"city,omitempty"`
	// State or province.
	State *string `json:"state,omitempty"`
	// Postal or ZIP code.
	Zipcode *string `json:"zipcode,omitempty"`
	// Country code.
	Country *string `json:"country,omitempty"`
}

// NewOrderBilling instantiates a new OrderBilling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderBilling() *OrderBilling {
	this := OrderBilling{}
	return &this
}

// NewOrderBillingWithDefaults instantiates a new OrderBilling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderBillingWithDefaults() *OrderBilling {
	this := OrderBilling{}
	return &this
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *OrderBilling) GetStreet() string {
	if o == nil || IsNil(o.Street) {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBilling) GetStreetOk() (*string, bool) {
	if o == nil || IsNil(o.Street) {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *OrderBilling) HasStreet() bool {
	if o != nil && !IsNil(o.Street) {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *OrderBilling) SetStreet(v string) {
	o.Street = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *OrderBilling) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBilling) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *OrderBilling) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *OrderBilling) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *OrderBilling) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBilling) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *OrderBilling) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *OrderBilling) SetState(v string) {
	o.State = &v
}

// GetZipcode returns the Zipcode field value if set, zero value otherwise.
func (o *OrderBilling) GetZipcode() string {
	if o == nil || IsNil(o.Zipcode) {
		var ret string
		return ret
	}
	return *o.Zipcode
}

// GetZipcodeOk returns a tuple with the Zipcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBilling) GetZipcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Zipcode) {
		return nil, false
	}
	return o.Zipcode, true
}

// HasZipcode returns a boolean if a field has been set.
func (o *OrderBilling) HasZipcode() bool {
	if o != nil && !IsNil(o.Zipcode) {
		return true
	}

	return false
}

// SetZipcode gets a reference to the given string and assigns it to the Zipcode field.
func (o *OrderBilling) SetZipcode(v string) {
	o.Zipcode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *OrderBilling) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderBilling) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *OrderBilling) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *OrderBilling) SetCountry(v string) {
	o.Country = &v
}

func (o OrderBilling) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderBilling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Street) {
		toSerialize["street"] = o.Street
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Zipcode) {
		toSerialize["zipcode"] = o.Zipcode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullableOrderBilling struct {
	value *OrderBilling
	isSet bool
}

func (v NullableOrderBilling) Get() *OrderBilling {
	return v.value
}

func (v *NullableOrderBilling) Set(val *OrderBilling) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderBilling(val *OrderBilling) *NullableOrderBilling {
	return &NullableOrderBilling{value: val, isSet: true}
}

func (v NullableOrderBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


