/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductsList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsList200Response{}

// ProductsList200Response struct for ProductsList200Response
type ProductsList200Response struct {
	Items []Product `json:"items"`
	Pagination ProductsList200ResponsePagination `json:"pagination"`
}

type _ProductsList200Response ProductsList200Response

// NewProductsList200Response instantiates a new ProductsList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsList200Response(items []Product, pagination ProductsList200ResponsePagination) *ProductsList200Response {
	this := ProductsList200Response{}
	this.Items = items
	this.Pagination = pagination
	return &this
}

// NewProductsList200ResponseWithDefaults instantiates a new ProductsList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsList200ResponseWithDefaults() *ProductsList200Response {
	this := ProductsList200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *ProductsList200Response) GetItems() []Product {
	if o == nil {
		var ret []Product
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ProductsList200Response) GetItemsOk() ([]Product, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ProductsList200Response) SetItems(v []Product) {
	o.Items = v
}

// GetPagination returns the Pagination field value
func (o *ProductsList200Response) GetPagination() ProductsList200ResponsePagination {
	if o == nil {
		var ret ProductsList200ResponsePagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ProductsList200Response) GetPaginationOk() (*ProductsList200ResponsePagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ProductsList200Response) SetPagination(v ProductsList200ResponsePagination) {
	o.Pagination = v
}

func (o ProductsList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *ProductsList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductsList200Response := _ProductsList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductsList200Response)

	if err != nil {
		return err
	}

	*o = ProductsList200Response(varProductsList200Response)

	return err
}

type NullableProductsList200Response struct {
	value *ProductsList200Response
	isSet bool
}

func (v NullableProductsList200Response) Get() *ProductsList200Response {
	return v.value
}

func (v *NullableProductsList200Response) Set(val *ProductsList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsList200Response(val *ProductsList200Response) *NullableProductsList200Response {
	return &NullableProductsList200Response{value: val, isSet: true}
}

func (v NullableProductsList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


