/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the UpdateEntitlementDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEntitlementDto{}

// UpdateEntitlementDto struct for UpdateEntitlementDto
type UpdateEntitlementDto struct {
	// The user-friendly name of the entitlement
	Name *string `json:"name,omitempty"`
	// The type of access to grant
	Type *string `json:"type,omitempty"`
	// The GitHub repository (e.g., owner/repo)
	GithubRepo *string `json:"githubRepo,omitempty"`
	// The GitHub repository permission level
	GithubPermission *string `json:"githubPermission,omitempty"`
	// The Discord Guild/Server ID
	DiscordGuildId *string `json:"discordGuildId,omitempty"`
	// The Discord Role ID to assign
	DiscordRoleId *string `json:"discordRoleId,omitempty"`
	// The associated Framer Template ID
	FramerTemplateId *string `json:"framerTemplateId,omitempty"`
	// The static License Key (if not dynamically generated)
	LicenseKey *string `json:"licenseKey,omitempty"`
	// The maximum activation limit for licenses
	ActivationLimit *float32 `json:"activationLimit,omitempty"`
	// A message shown to the user upon license activation
	ActivationMessage *string `json:"activationMessage,omitempty"`
	// The number of hours until the entitlement expires
	ExpiryHours *float32 `json:"expiryHours,omitempty"`
	// The digital download URL or redirect link
	DigitalLink *string `json:"digitalLink,omitempty"`
	// Custom setup instructions for the user
	Instructions *string `json:"instructions,omitempty"`
}

// NewUpdateEntitlementDto instantiates a new UpdateEntitlementDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEntitlementDto() *UpdateEntitlementDto {
	this := UpdateEntitlementDto{}
	var githubPermission string = "pull"
	this.GithubPermission = &githubPermission
	return &this
}

// NewUpdateEntitlementDtoWithDefaults instantiates a new UpdateEntitlementDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEntitlementDtoWithDefaults() *UpdateEntitlementDto {
	this := UpdateEntitlementDto{}
	var githubPermission string = "pull"
	this.GithubPermission = &githubPermission
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEntitlementDto) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UpdateEntitlementDto) SetType(v string) {
	o.Type = &v
}

// GetGithubRepo returns the GithubRepo field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetGithubRepo() string {
	if o == nil || IsNil(o.GithubRepo) {
		var ret string
		return ret
	}
	return *o.GithubRepo
}

// GetGithubRepoOk returns a tuple with the GithubRepo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetGithubRepoOk() (*string, bool) {
	if o == nil || IsNil(o.GithubRepo) {
		return nil, false
	}
	return o.GithubRepo, true
}

// HasGithubRepo returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasGithubRepo() bool {
	if o != nil && !IsNil(o.GithubRepo) {
		return true
	}

	return false
}

// SetGithubRepo gets a reference to the given string and assigns it to the GithubRepo field.
func (o *UpdateEntitlementDto) SetGithubRepo(v string) {
	o.GithubRepo = &v
}

// GetGithubPermission returns the GithubPermission field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetGithubPermission() string {
	if o == nil || IsNil(o.GithubPermission) {
		var ret string
		return ret
	}
	return *o.GithubPermission
}

// GetGithubPermissionOk returns a tuple with the GithubPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetGithubPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.GithubPermission) {
		return nil, false
	}
	return o.GithubPermission, true
}

// HasGithubPermission returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasGithubPermission() bool {
	if o != nil && !IsNil(o.GithubPermission) {
		return true
	}

	return false
}

// SetGithubPermission gets a reference to the given string and assigns it to the GithubPermission field.
func (o *UpdateEntitlementDto) SetGithubPermission(v string) {
	o.GithubPermission = &v
}

// GetDiscordGuildId returns the DiscordGuildId field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetDiscordGuildId() string {
	if o == nil || IsNil(o.DiscordGuildId) {
		var ret string
		return ret
	}
	return *o.DiscordGuildId
}

// GetDiscordGuildIdOk returns a tuple with the DiscordGuildId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetDiscordGuildIdOk() (*string, bool) {
	if o == nil || IsNil(o.DiscordGuildId) {
		return nil, false
	}
	return o.DiscordGuildId, true
}

// HasDiscordGuildId returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasDiscordGuildId() bool {
	if o != nil && !IsNil(o.DiscordGuildId) {
		return true
	}

	return false
}

// SetDiscordGuildId gets a reference to the given string and assigns it to the DiscordGuildId field.
func (o *UpdateEntitlementDto) SetDiscordGuildId(v string) {
	o.DiscordGuildId = &v
}

// GetDiscordRoleId returns the DiscordRoleId field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetDiscordRoleId() string {
	if o == nil || IsNil(o.DiscordRoleId) {
		var ret string
		return ret
	}
	return *o.DiscordRoleId
}

// GetDiscordRoleIdOk returns a tuple with the DiscordRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetDiscordRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.DiscordRoleId) {
		return nil, false
	}
	return o.DiscordRoleId, true
}

// HasDiscordRoleId returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasDiscordRoleId() bool {
	if o != nil && !IsNil(o.DiscordRoleId) {
		return true
	}

	return false
}

// SetDiscordRoleId gets a reference to the given string and assigns it to the DiscordRoleId field.
func (o *UpdateEntitlementDto) SetDiscordRoleId(v string) {
	o.DiscordRoleId = &v
}

// GetFramerTemplateId returns the FramerTemplateId field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetFramerTemplateId() string {
	if o == nil || IsNil(o.FramerTemplateId) {
		var ret string
		return ret
	}
	return *o.FramerTemplateId
}

// GetFramerTemplateIdOk returns a tuple with the FramerTemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetFramerTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.FramerTemplateId) {
		return nil, false
	}
	return o.FramerTemplateId, true
}

// HasFramerTemplateId returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasFramerTemplateId() bool {
	if o != nil && !IsNil(o.FramerTemplateId) {
		return true
	}

	return false
}

// SetFramerTemplateId gets a reference to the given string and assigns it to the FramerTemplateId field.
func (o *UpdateEntitlementDto) SetFramerTemplateId(v string) {
	o.FramerTemplateId = &v
}

// GetLicenseKey returns the LicenseKey field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetLicenseKey() string {
	if o == nil || IsNil(o.LicenseKey) {
		var ret string
		return ret
	}
	return *o.LicenseKey
}

// GetLicenseKeyOk returns a tuple with the LicenseKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetLicenseKeyOk() (*string, bool) {
	if o == nil || IsNil(o.LicenseKey) {
		return nil, false
	}
	return o.LicenseKey, true
}

// HasLicenseKey returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasLicenseKey() bool {
	if o != nil && !IsNil(o.LicenseKey) {
		return true
	}

	return false
}

// SetLicenseKey gets a reference to the given string and assigns it to the LicenseKey field.
func (o *UpdateEntitlementDto) SetLicenseKey(v string) {
	o.LicenseKey = &v
}

// GetActivationLimit returns the ActivationLimit field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetActivationLimit() float32 {
	if o == nil || IsNil(o.ActivationLimit) {
		var ret float32
		return ret
	}
	return *o.ActivationLimit
}

// GetActivationLimitOk returns a tuple with the ActivationLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetActivationLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.ActivationLimit) {
		return nil, false
	}
	return o.ActivationLimit, true
}

// HasActivationLimit returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasActivationLimit() bool {
	if o != nil && !IsNil(o.ActivationLimit) {
		return true
	}

	return false
}

// SetActivationLimit gets a reference to the given float32 and assigns it to the ActivationLimit field.
func (o *UpdateEntitlementDto) SetActivationLimit(v float32) {
	o.ActivationLimit = &v
}

// GetActivationMessage returns the ActivationMessage field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetActivationMessage() string {
	if o == nil || IsNil(o.ActivationMessage) {
		var ret string
		return ret
	}
	return *o.ActivationMessage
}

// GetActivationMessageOk returns a tuple with the ActivationMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetActivationMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ActivationMessage) {
		return nil, false
	}
	return o.ActivationMessage, true
}

// HasActivationMessage returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasActivationMessage() bool {
	if o != nil && !IsNil(o.ActivationMessage) {
		return true
	}

	return false
}

// SetActivationMessage gets a reference to the given string and assigns it to the ActivationMessage field.
func (o *UpdateEntitlementDto) SetActivationMessage(v string) {
	o.ActivationMessage = &v
}

// GetExpiryHours returns the ExpiryHours field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetExpiryHours() float32 {
	if o == nil || IsNil(o.ExpiryHours) {
		var ret float32
		return ret
	}
	return *o.ExpiryHours
}

// GetExpiryHoursOk returns a tuple with the ExpiryHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetExpiryHoursOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpiryHours) {
		return nil, false
	}
	return o.ExpiryHours, true
}

// HasExpiryHours returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasExpiryHours() bool {
	if o != nil && !IsNil(o.ExpiryHours) {
		return true
	}

	return false
}

// SetExpiryHours gets a reference to the given float32 and assigns it to the ExpiryHours field.
func (o *UpdateEntitlementDto) SetExpiryHours(v float32) {
	o.ExpiryHours = &v
}

// GetDigitalLink returns the DigitalLink field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetDigitalLink() string {
	if o == nil || IsNil(o.DigitalLink) {
		var ret string
		return ret
	}
	return *o.DigitalLink
}

// GetDigitalLinkOk returns a tuple with the DigitalLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetDigitalLinkOk() (*string, bool) {
	if o == nil || IsNil(o.DigitalLink) {
		return nil, false
	}
	return o.DigitalLink, true
}

// HasDigitalLink returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasDigitalLink() bool {
	if o != nil && !IsNil(o.DigitalLink) {
		return true
	}

	return false
}

// SetDigitalLink gets a reference to the given string and assigns it to the DigitalLink field.
func (o *UpdateEntitlementDto) SetDigitalLink(v string) {
	o.DigitalLink = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *UpdateEntitlementDto) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEntitlementDto) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *UpdateEntitlementDto) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *UpdateEntitlementDto) SetInstructions(v string) {
	o.Instructions = &v
}

func (o UpdateEntitlementDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEntitlementDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.GithubRepo) {
		toSerialize["githubRepo"] = o.GithubRepo
	}
	if !IsNil(o.GithubPermission) {
		toSerialize["githubPermission"] = o.GithubPermission
	}
	if !IsNil(o.DiscordGuildId) {
		toSerialize["discordGuildId"] = o.DiscordGuildId
	}
	if !IsNil(o.DiscordRoleId) {
		toSerialize["discordRoleId"] = o.DiscordRoleId
	}
	if !IsNil(o.FramerTemplateId) {
		toSerialize["framerTemplateId"] = o.FramerTemplateId
	}
	if !IsNil(o.LicenseKey) {
		toSerialize["licenseKey"] = o.LicenseKey
	}
	if !IsNil(o.ActivationLimit) {
		toSerialize["activationLimit"] = o.ActivationLimit
	}
	if !IsNil(o.ActivationMessage) {
		toSerialize["activationMessage"] = o.ActivationMessage
	}
	if !IsNil(o.ExpiryHours) {
		toSerialize["expiryHours"] = o.ExpiryHours
	}
	if !IsNil(o.DigitalLink) {
		toSerialize["digitalLink"] = o.DigitalLink
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	return toSerialize, nil
}

type NullableUpdateEntitlementDto struct {
	value *UpdateEntitlementDto
	isSet bool
}

func (v NullableUpdateEntitlementDto) Get() *UpdateEntitlementDto {
	return v.value
}

func (v *NullableUpdateEntitlementDto) Set(val *UpdateEntitlementDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEntitlementDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEntitlementDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEntitlementDto(val *UpdateEntitlementDto) *NullableUpdateEntitlementDto {
	return &NullableUpdateEntitlementDto{value: val, isSet: true}
}

func (v NullableUpdateEntitlementDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEntitlementDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


