/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutVerificationList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutVerificationList{}

// PayoutVerificationList struct for PayoutVerificationList
type PayoutVerificationList struct {
	// List of verifications for the payout account
	Data []PayoutVerification `json:"data"`
}

type _PayoutVerificationList PayoutVerificationList

// NewPayoutVerificationList instantiates a new PayoutVerificationList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutVerificationList(data []PayoutVerification) *PayoutVerificationList {
	this := PayoutVerificationList{}
	this.Data = data
	return &this
}

// NewPayoutVerificationListWithDefaults instantiates a new PayoutVerificationList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutVerificationListWithDefaults() *PayoutVerificationList {
	this := PayoutVerificationList{}
	return &this
}

// GetData returns the Data field value
func (o *PayoutVerificationList) GetData() []PayoutVerification {
	if o == nil {
		var ret []PayoutVerification
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PayoutVerificationList) GetDataOk() ([]PayoutVerification, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PayoutVerificationList) SetData(v []PayoutVerification) {
	o.Data = v
}

func (o PayoutVerificationList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutVerificationList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PayoutVerificationList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutVerificationList := _PayoutVerificationList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutVerificationList)

	if err != nil {
		return err
	}

	*o = PayoutVerificationList(varPayoutVerificationList)

	return err
}

type NullablePayoutVerificationList struct {
	value *PayoutVerificationList
	isSet bool
}

func (v NullablePayoutVerificationList) Get() *PayoutVerificationList {
	return v.value
}

func (v *NullablePayoutVerificationList) Set(val *PayoutVerificationList) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutVerificationList) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutVerificationList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutVerificationList(val *PayoutVerificationList) *NullablePayoutVerificationList {
	return &NullablePayoutVerificationList{value: val, isSet: true}
}

func (v NullablePayoutVerificationList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutVerificationList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


