/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateFramerTemplateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFramerTemplateDto{}

// CreateFramerTemplateDto struct for CreateFramerTemplateDto
type CreateFramerTemplateDto struct {
	// The name of the Framer template.
	Name string `json:"name"`
	// The public Framer remix link.
	RemixLink string `json:"remixLink"`
	// A brief description of the template.
	Description *string `json:"description,omitempty"`
}

type _CreateFramerTemplateDto CreateFramerTemplateDto

// NewCreateFramerTemplateDto instantiates a new CreateFramerTemplateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFramerTemplateDto(name string, remixLink string) *CreateFramerTemplateDto {
	this := CreateFramerTemplateDto{}
	this.Name = name
	this.RemixLink = remixLink
	return &this
}

// NewCreateFramerTemplateDtoWithDefaults instantiates a new CreateFramerTemplateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFramerTemplateDtoWithDefaults() *CreateFramerTemplateDto {
	this := CreateFramerTemplateDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateFramerTemplateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateFramerTemplateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateFramerTemplateDto) SetName(v string) {
	o.Name = v
}

// GetRemixLink returns the RemixLink field value
func (o *CreateFramerTemplateDto) GetRemixLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemixLink
}

// GetRemixLinkOk returns a tuple with the RemixLink field value
// and a boolean to check if the value has been set.
func (o *CreateFramerTemplateDto) GetRemixLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemixLink, true
}

// SetRemixLink sets field value
func (o *CreateFramerTemplateDto) SetRemixLink(v string) {
	o.RemixLink = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateFramerTemplateDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFramerTemplateDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateFramerTemplateDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateFramerTemplateDto) SetDescription(v string) {
	o.Description = &v
}

func (o CreateFramerTemplateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFramerTemplateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["remixLink"] = o.RemixLink
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateFramerTemplateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"remixLink",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFramerTemplateDto := _CreateFramerTemplateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFramerTemplateDto)

	if err != nil {
		return err
	}

	*o = CreateFramerTemplateDto(varCreateFramerTemplateDto)

	return err
}

type NullableCreateFramerTemplateDto struct {
	value *CreateFramerTemplateDto
	isSet bool
}

func (v NullableCreateFramerTemplateDto) Get() *CreateFramerTemplateDto {
	return v.value
}

func (v *NullableCreateFramerTemplateDto) Set(val *CreateFramerTemplateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFramerTemplateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFramerTemplateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFramerTemplateDto(val *CreateFramerTemplateDto) *NullableCreateFramerTemplateDto {
	return &NullableCreateFramerTemplateDto{value: val, isSet: true}
}

func (v NullableCreateFramerTemplateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFramerTemplateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


