/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DisputeListMetaDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeListMetaDto{}

// DisputeListMetaDto struct for DisputeListMetaDto
type DisputeListMetaDto struct {
	// Total count of disputes
	Total float32 `json:"total"`
	// Current page number
	Page float32 `json:"page"`
	// Limit of items per page
	Limit float32 `json:"limit"`
	// Total number of pages
	TotalPages float32 `json:"totalPages"`
}

type _DisputeListMetaDto DisputeListMetaDto

// NewDisputeListMetaDto instantiates a new DisputeListMetaDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisputeListMetaDto(total float32, page float32, limit float32, totalPages float32) *DisputeListMetaDto {
	this := DisputeListMetaDto{}
	this.Total = total
	this.Page = page
	this.Limit = limit
	this.TotalPages = totalPages
	return &this
}

// NewDisputeListMetaDtoWithDefaults instantiates a new DisputeListMetaDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisputeListMetaDtoWithDefaults() *DisputeListMetaDto {
	this := DisputeListMetaDto{}
	return &this
}

// GetTotal returns the Total field value
func (o *DisputeListMetaDto) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DisputeListMetaDto) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DisputeListMetaDto) SetTotal(v float32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *DisputeListMetaDto) GetPage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *DisputeListMetaDto) GetPageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *DisputeListMetaDto) SetPage(v float32) {
	o.Page = v
}

// GetLimit returns the Limit field value
func (o *DisputeListMetaDto) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *DisputeListMetaDto) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *DisputeListMetaDto) SetLimit(v float32) {
	o.Limit = v
}

// GetTotalPages returns the TotalPages field value
func (o *DisputeListMetaDto) GetTotalPages() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *DisputeListMetaDto) GetTotalPagesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *DisputeListMetaDto) SetTotalPages(v float32) {
	o.TotalPages = v
}

func (o DisputeListMetaDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisputeListMetaDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["limit"] = o.Limit
	toSerialize["totalPages"] = o.TotalPages
	return toSerialize, nil
}

func (o *DisputeListMetaDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"page",
		"limit",
		"totalPages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisputeListMetaDto := _DisputeListMetaDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisputeListMetaDto)

	if err != nil {
		return err
	}

	*o = DisputeListMetaDto(varDisputeListMetaDto)

	return err
}

type NullableDisputeListMetaDto struct {
	value *DisputeListMetaDto
	isSet bool
}

func (v NullableDisputeListMetaDto) Get() *DisputeListMetaDto {
	return v.value
}

func (v *NullableDisputeListMetaDto) Set(val *DisputeListMetaDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeListMetaDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeListMetaDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeListMetaDto(val *DisputeListMetaDto) *NullableDisputeListMetaDto {
	return &NullableDisputeListMetaDto{value: val, isSet: true}
}

func (v NullableDisputeListMetaDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeListMetaDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


