/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PayoutAccessToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutAccessToken{}

// PayoutAccessToken struct for PayoutAccessToken
type PayoutAccessToken struct {
	// The temporary access token for embed portals
	AccessToken string `json:"access_token"`
	// Expiration timestamp of the access token
	ExpiresAt time.Time `json:"expires_at"`
}

type _PayoutAccessToken PayoutAccessToken

// NewPayoutAccessToken instantiates a new PayoutAccessToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutAccessToken(accessToken string, expiresAt time.Time) *PayoutAccessToken {
	this := PayoutAccessToken{}
	this.AccessToken = accessToken
	this.ExpiresAt = expiresAt
	return &this
}

// NewPayoutAccessTokenWithDefaults instantiates a new PayoutAccessToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutAccessTokenWithDefaults() *PayoutAccessToken {
	this := PayoutAccessToken{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *PayoutAccessToken) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *PayoutAccessToken) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *PayoutAccessToken) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *PayoutAccessToken) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *PayoutAccessToken) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *PayoutAccessToken) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o PayoutAccessToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutAccessToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *PayoutAccessToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutAccessToken := _PayoutAccessToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutAccessToken)

	if err != nil {
		return err
	}

	*o = PayoutAccessToken(varPayoutAccessToken)

	return err
}

type NullablePayoutAccessToken struct {
	value *PayoutAccessToken
	isSet bool
}

func (v NullablePayoutAccessToken) Get() *PayoutAccessToken {
	return v.value
}

func (v *NullablePayoutAccessToken) Set(val *PayoutAccessToken) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutAccessToken) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutAccessToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutAccessToken(val *PayoutAccessToken) *NullablePayoutAccessToken {
	return &NullablePayoutAccessToken{value: val, isSet: true}
}

func (v NullablePayoutAccessToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutAccessToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


