/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the UpdateCheckoutLinkDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCheckoutLinkDto{}

// UpdateCheckoutLinkDto struct for UpdateCheckoutLinkDto
type UpdateCheckoutLinkDto struct {
	// The friendly display title of this checkout link
	Title *string `json:"title,omitempty"`
	// Product database/Whop ID to sell
	ProductId *string `json:"productId,omitempty"`
	// Optional collection database ID to sell
	CollectionId *string `json:"collectionId,omitempty"`
	// Prefilled customer name for checkout inputs
	CustomerName *string `json:"customerName,omitempty"`
	// Prefilled customer email for checkout inputs
	CustomerEmail *string `json:"customerEmail,omitempty"`
	// Prefilled customer billing address line 1
	AddressLine1 *string `json:"addressLine1,omitempty"`
	// Prefilled customer billing city
	City *string `json:"city,omitempty"`
	// Prefilled customer billing state
	State *string `json:"state,omitempty"`
	// Prefilled customer billing zip/postal code
	PostalCode *string `json:"postalCode,omitempty"`
	// Prefilled customer billing country (2-letter ISO)
	Country *string `json:"country,omitempty"`
	// Override quantity for checkout session
	Quantity map[string]interface{} `json:"quantity,omitempty"`
	// The absolute URL to redirect to upon successful payment completion
	RedirectUrl *string `json:"redirectUrl,omitempty"`
	// The absolute URL to redirect to if a customer cancels the payment
	CancelUrl *string `json:"cancelUrl,omitempty"`
	// Whether to display discount input form fields on checkout screen
	ShowDiscounts *bool `json:"showDiscounts,omitempty"`
}

// NewUpdateCheckoutLinkDto instantiates a new UpdateCheckoutLinkDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCheckoutLinkDto() *UpdateCheckoutLinkDto {
	this := UpdateCheckoutLinkDto{}
	var showDiscounts bool = true
	this.ShowDiscounts = &showDiscounts
	return &this
}

// NewUpdateCheckoutLinkDtoWithDefaults instantiates a new UpdateCheckoutLinkDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCheckoutLinkDtoWithDefaults() *UpdateCheckoutLinkDto {
	this := UpdateCheckoutLinkDto{}
	var showDiscounts bool = true
	this.ShowDiscounts = &showDiscounts
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateCheckoutLinkDto) SetTitle(v string) {
	o.Title = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *UpdateCheckoutLinkDto) SetProductId(v string) {
	o.ProductId = &v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCollectionId() string {
	if o == nil || IsNil(o.CollectionId) {
		var ret string
		return ret
	}
	return *o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionId) {
		return nil, false
	}
	return o.CollectionId, true
}

// HasCollectionId returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCollectionId() bool {
	if o != nil && !IsNil(o.CollectionId) {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given string and assigns it to the CollectionId field.
func (o *UpdateCheckoutLinkDto) SetCollectionId(v string) {
	o.CollectionId = &v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *UpdateCheckoutLinkDto) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail) {
		var ret string
		return ret
	}
	return *o.CustomerEmail
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCustomerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerEmail) {
		return nil, false
	}
	return o.CustomerEmail, true
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCustomerEmail() bool {
	if o != nil && !IsNil(o.CustomerEmail) {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given string and assigns it to the CustomerEmail field.
func (o *UpdateCheckoutLinkDto) SetCustomerEmail(v string) {
	o.CustomerEmail = &v
}

// GetAddressLine1 returns the AddressLine1 field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetAddressLine1() string {
	if o == nil || IsNil(o.AddressLine1) {
		var ret string
		return ret
	}
	return *o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetAddressLine1Ok() (*string, bool) {
	if o == nil || IsNil(o.AddressLine1) {
		return nil, false
	}
	return o.AddressLine1, true
}

// HasAddressLine1 returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasAddressLine1() bool {
	if o != nil && !IsNil(o.AddressLine1) {
		return true
	}

	return false
}

// SetAddressLine1 gets a reference to the given string and assigns it to the AddressLine1 field.
func (o *UpdateCheckoutLinkDto) SetAddressLine1(v string) {
	o.AddressLine1 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *UpdateCheckoutLinkDto) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *UpdateCheckoutLinkDto) SetState(v string) {
	o.State = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *UpdateCheckoutLinkDto) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *UpdateCheckoutLinkDto) SetCountry(v string) {
	o.Country = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetQuantity() map[string]interface{} {
	if o == nil || IsNil(o.Quantity) {
		var ret map[string]interface{}
		return ret
	}
	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetQuantityOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Quantity) {
		return map[string]interface{}{}, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given map[string]interface{} and assigns it to the Quantity field.
func (o *UpdateCheckoutLinkDto) SetQuantity(v map[string]interface{}) {
	o.Quantity = v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetRedirectUrl() string {
	if o == nil || IsNil(o.RedirectUrl) {
		var ret string
		return ret
	}
	return *o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return o.RedirectUrl, true
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasRedirectUrl() bool {
	if o != nil && !IsNil(o.RedirectUrl) {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given string and assigns it to the RedirectUrl field.
func (o *UpdateCheckoutLinkDto) SetRedirectUrl(v string) {
	o.RedirectUrl = &v
}

// GetCancelUrl returns the CancelUrl field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetCancelUrl() string {
	if o == nil || IsNil(o.CancelUrl) {
		var ret string
		return ret
	}
	return *o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetCancelUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CancelUrl) {
		return nil, false
	}
	return o.CancelUrl, true
}

// HasCancelUrl returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasCancelUrl() bool {
	if o != nil && !IsNil(o.CancelUrl) {
		return true
	}

	return false
}

// SetCancelUrl gets a reference to the given string and assigns it to the CancelUrl field.
func (o *UpdateCheckoutLinkDto) SetCancelUrl(v string) {
	o.CancelUrl = &v
}

// GetShowDiscounts returns the ShowDiscounts field value if set, zero value otherwise.
func (o *UpdateCheckoutLinkDto) GetShowDiscounts() bool {
	if o == nil || IsNil(o.ShowDiscounts) {
		var ret bool
		return ret
	}
	return *o.ShowDiscounts
}

// GetShowDiscountsOk returns a tuple with the ShowDiscounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCheckoutLinkDto) GetShowDiscountsOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowDiscounts) {
		return nil, false
	}
	return o.ShowDiscounts, true
}

// HasShowDiscounts returns a boolean if a field has been set.
func (o *UpdateCheckoutLinkDto) HasShowDiscounts() bool {
	if o != nil && !IsNil(o.ShowDiscounts) {
		return true
	}

	return false
}

// SetShowDiscounts gets a reference to the given bool and assigns it to the ShowDiscounts field.
func (o *UpdateCheckoutLinkDto) SetShowDiscounts(v bool) {
	o.ShowDiscounts = &v
}

func (o UpdateCheckoutLinkDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCheckoutLinkDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !IsNil(o.CollectionId) {
		toSerialize["collectionId"] = o.CollectionId
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customerEmail"] = o.CustomerEmail
	}
	if !IsNil(o.AddressLine1) {
		toSerialize["addressLine1"] = o.AddressLine1
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.RedirectUrl) {
		toSerialize["redirectUrl"] = o.RedirectUrl
	}
	if !IsNil(o.CancelUrl) {
		toSerialize["cancelUrl"] = o.CancelUrl
	}
	if !IsNil(o.ShowDiscounts) {
		toSerialize["showDiscounts"] = o.ShowDiscounts
	}
	return toSerialize, nil
}

type NullableUpdateCheckoutLinkDto struct {
	value *UpdateCheckoutLinkDto
	isSet bool
}

func (v NullableUpdateCheckoutLinkDto) Get() *UpdateCheckoutLinkDto {
	return v.value
}

func (v *NullableUpdateCheckoutLinkDto) Set(val *UpdateCheckoutLinkDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCheckoutLinkDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCheckoutLinkDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCheckoutLinkDto(val *UpdateCheckoutLinkDto) *NullableUpdateCheckoutLinkDto {
	return &NullableUpdateCheckoutLinkDto{value: val, isSet: true}
}

func (v NullableUpdateCheckoutLinkDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCheckoutLinkDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


