/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutMethod{}

// PayoutMethod struct for PayoutMethod
type PayoutMethod struct {
	// The payout method ID
	Id string `json:"id"`
	// Type of payout method (e.g. bank_account, stripe)
	Type string `json:"type"`
	// Status of the payout method
	Status string `json:"status"`
	// Metadata and details of the bank/card associated
	Details map[string]interface{} `json:"details,omitempty"`
}

type _PayoutMethod PayoutMethod

// NewPayoutMethod instantiates a new PayoutMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutMethod(id string, type_ string, status string) *PayoutMethod {
	this := PayoutMethod{}
	this.Id = id
	this.Type = type_
	this.Status = status
	return &this
}

// NewPayoutMethodWithDefaults instantiates a new PayoutMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutMethodWithDefaults() *PayoutMethod {
	this := PayoutMethod{}
	return &this
}

// GetId returns the Id field value
func (o *PayoutMethod) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PayoutMethod) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PayoutMethod) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PayoutMethod) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PayoutMethod) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PayoutMethod) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *PayoutMethod) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PayoutMethod) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PayoutMethod) SetStatus(v string) {
	o.Status = v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *PayoutMethod) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutMethod) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *PayoutMethod) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *PayoutMethod) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o PayoutMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

func (o *PayoutMethod) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutMethod := _PayoutMethod{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutMethod)

	if err != nil {
		return err
	}

	*o = PayoutMethod(varPayoutMethod)

	return err
}

type NullablePayoutMethod struct {
	value *PayoutMethod
	isSet bool
}

func (v NullablePayoutMethod) Get() *PayoutMethod {
	return v.value
}

func (v *NullablePayoutMethod) Set(val *PayoutMethod) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutMethod) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutMethod(val *PayoutMethod) *NullablePayoutMethod {
	return &NullablePayoutMethod{value: val, isSet: true}
}

func (v NullablePayoutMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


