/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
)

// checks if the DiscountUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscountUpdate{}

// DiscountUpdate struct for DiscountUpdate
type DiscountUpdate struct {
	// Customer-facing name of the discount.
	Name *string `json:"name,omitempty"`
	// Calculation type: percentage or fixed_amount.
	Type *string `json:"type,omitempty"`
	// The discount value.
	Amount *float32 `json:"amount,omitempty"`
	// Maximum number of redemptions allowed.
	UsageLimit NullableInt32 `json:"usage_limit,omitempty"`
	// Expiration timestamp for the discount.
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	// Number of subscription cycles this discount applies to.
	SubscriptionCycles NullableInt32 `json:"subscription_cycles,omitempty"`
	// List of product IDs this discount is restricted to.
	RestrictedTo []string `json:"restricted_to,omitempty"`
	// Whether to preserve the discount when subscription plan changes.
	PreserveOnPlanChange *bool `json:"preserve_on_plan_change,omitempty"`
	// Custom metadata for the discount.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewDiscountUpdate instantiates a new DiscountUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscountUpdate() *DiscountUpdate {
	this := DiscountUpdate{}
	return &this
}

// NewDiscountUpdateWithDefaults instantiates a new DiscountUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscountUpdateWithDefaults() *DiscountUpdate {
	this := DiscountUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DiscountUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DiscountUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DiscountUpdate) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DiscountUpdate) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DiscountUpdate) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DiscountUpdate) SetType(v string) {
	o.Type = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DiscountUpdate) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DiscountUpdate) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *DiscountUpdate) SetAmount(v float32) {
	o.Amount = &v
}

// GetUsageLimit returns the UsageLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiscountUpdate) GetUsageLimit() int32 {
	if o == nil || IsNil(o.UsageLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.UsageLimit.Get()
}

// GetUsageLimitOk returns a tuple with the UsageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiscountUpdate) GetUsageLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageLimit.Get(), o.UsageLimit.IsSet()
}

// HasUsageLimit returns a boolean if a field has been set.
func (o *DiscountUpdate) HasUsageLimit() bool {
	if o != nil && o.UsageLimit.IsSet() {
		return true
	}

	return false
}

// SetUsageLimit gets a reference to the given NullableInt32 and assigns it to the UsageLimit field.
func (o *DiscountUpdate) SetUsageLimit(v int32) {
	o.UsageLimit.Set(&v)
}
// SetUsageLimitNil sets the value for UsageLimit to be an explicit nil
func (o *DiscountUpdate) SetUsageLimitNil() {
	o.UsageLimit.Set(nil)
}

// UnsetUsageLimit ensures that no value is present for UsageLimit, not even an explicit nil
func (o *DiscountUpdate) UnsetUsageLimit() {
	o.UsageLimit.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiscountUpdate) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiscountUpdate) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *DiscountUpdate) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *DiscountUpdate) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *DiscountUpdate) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *DiscountUpdate) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetSubscriptionCycles returns the SubscriptionCycles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiscountUpdate) GetSubscriptionCycles() int32 {
	if o == nil || IsNil(o.SubscriptionCycles.Get()) {
		var ret int32
		return ret
	}
	return *o.SubscriptionCycles.Get()
}

// GetSubscriptionCyclesOk returns a tuple with the SubscriptionCycles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiscountUpdate) GetSubscriptionCyclesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionCycles.Get(), o.SubscriptionCycles.IsSet()
}

// HasSubscriptionCycles returns a boolean if a field has been set.
func (o *DiscountUpdate) HasSubscriptionCycles() bool {
	if o != nil && o.SubscriptionCycles.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionCycles gets a reference to the given NullableInt32 and assigns it to the SubscriptionCycles field.
func (o *DiscountUpdate) SetSubscriptionCycles(v int32) {
	o.SubscriptionCycles.Set(&v)
}
// SetSubscriptionCyclesNil sets the value for SubscriptionCycles to be an explicit nil
func (o *DiscountUpdate) SetSubscriptionCyclesNil() {
	o.SubscriptionCycles.Set(nil)
}

// UnsetSubscriptionCycles ensures that no value is present for SubscriptionCycles, not even an explicit nil
func (o *DiscountUpdate) UnsetSubscriptionCycles() {
	o.SubscriptionCycles.Unset()
}

// GetRestrictedTo returns the RestrictedTo field value if set, zero value otherwise.
func (o *DiscountUpdate) GetRestrictedTo() []string {
	if o == nil || IsNil(o.RestrictedTo) {
		var ret []string
		return ret
	}
	return o.RestrictedTo
}

// GetRestrictedToOk returns a tuple with the RestrictedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetRestrictedToOk() ([]string, bool) {
	if o == nil || IsNil(o.RestrictedTo) {
		return nil, false
	}
	return o.RestrictedTo, true
}

// HasRestrictedTo returns a boolean if a field has been set.
func (o *DiscountUpdate) HasRestrictedTo() bool {
	if o != nil && !IsNil(o.RestrictedTo) {
		return true
	}

	return false
}

// SetRestrictedTo gets a reference to the given []string and assigns it to the RestrictedTo field.
func (o *DiscountUpdate) SetRestrictedTo(v []string) {
	o.RestrictedTo = v
}

// GetPreserveOnPlanChange returns the PreserveOnPlanChange field value if set, zero value otherwise.
func (o *DiscountUpdate) GetPreserveOnPlanChange() bool {
	if o == nil || IsNil(o.PreserveOnPlanChange) {
		var ret bool
		return ret
	}
	return *o.PreserveOnPlanChange
}

// GetPreserveOnPlanChangeOk returns a tuple with the PreserveOnPlanChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetPreserveOnPlanChangeOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveOnPlanChange) {
		return nil, false
	}
	return o.PreserveOnPlanChange, true
}

// HasPreserveOnPlanChange returns a boolean if a field has been set.
func (o *DiscountUpdate) HasPreserveOnPlanChange() bool {
	if o != nil && !IsNil(o.PreserveOnPlanChange) {
		return true
	}

	return false
}

// SetPreserveOnPlanChange gets a reference to the given bool and assigns it to the PreserveOnPlanChange field.
func (o *DiscountUpdate) SetPreserveOnPlanChange(v bool) {
	o.PreserveOnPlanChange = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DiscountUpdate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscountUpdate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DiscountUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *DiscountUpdate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o DiscountUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscountUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if o.UsageLimit.IsSet() {
		toSerialize["usage_limit"] = o.UsageLimit.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.SubscriptionCycles.IsSet() {
		toSerialize["subscription_cycles"] = o.SubscriptionCycles.Get()
	}
	if !IsNil(o.RestrictedTo) {
		toSerialize["restricted_to"] = o.RestrictedTo
	}
	if !IsNil(o.PreserveOnPlanChange) {
		toSerialize["preserve_on_plan_change"] = o.PreserveOnPlanChange
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableDiscountUpdate struct {
	value *DiscountUpdate
	isSet bool
}

func (v NullableDiscountUpdate) Get() *DiscountUpdate {
	return v.value
}

func (v *NullableDiscountUpdate) Set(val *DiscountUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscountUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscountUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscountUpdate(val *DiscountUpdate) *NullableDiscountUpdate {
	return &NullableDiscountUpdate{value: val, isSet: true}
}

func (v NullableDiscountUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscountUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


