/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MeterResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeterResponseDto{}

// MeterResponseDto Represents a usage meter configured for event-based billing, including the tracked event name, aggregation strategy, optional filters, and archive status.
type MeterResponseDto struct {
	// The unique meter ID.
	Id string `json:"id"`
	// The business ID that owns this meter.
	BusinessId string `json:"businessId"`
	// Meter display name.
	Name string `json:"name"`
	// Meter description.
	Description map[string]interface{} `json:"description,omitempty"`
	// The event name tracked by this meter.
	EventName string `json:"eventName"`
	// Aggregation strategy for usage events.
	AggregationType string `json:"aggregationType"`
	// Metadata key used for aggregation.
	AggregationKey map[string]interface{} `json:"aggregationKey,omitempty"`
	// Measurement unit label.
	Unit map[string]interface{} `json:"unit,omitempty"`
	// Optional filter definition for advanced matching.
	Filters map[string]interface{} `json:"filters,omitempty"`
	// Whether the meter is archived.
	Archived bool `json:"archived"`
	// Creation timestamp.
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

type _MeterResponseDto MeterResponseDto

// NewMeterResponseDto instantiates a new MeterResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeterResponseDto(id string, businessId string, name string, eventName string, aggregationType string, archived bool, createdAt time.Time, updatedAt time.Time) *MeterResponseDto {
	this := MeterResponseDto{}
	this.Id = id
	this.BusinessId = businessId
	this.Name = name
	this.EventName = eventName
	this.AggregationType = aggregationType
	this.Archived = archived
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewMeterResponseDtoWithDefaults instantiates a new MeterResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterResponseDtoWithDefaults() *MeterResponseDto {
	this := MeterResponseDto{}
	return &this
}

// GetId returns the Id field value
func (o *MeterResponseDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MeterResponseDto) SetId(v string) {
	o.Id = v
}

// GetBusinessId returns the BusinessId field value
func (o *MeterResponseDto) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *MeterResponseDto) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetName returns the Name field value
func (o *MeterResponseDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MeterResponseDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MeterResponseDto) GetDescription() map[string]interface{} {
	if o == nil || IsNil(o.Description) {
		var ret map[string]interface{}
		return ret
	}
	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetDescriptionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return map[string]interface{}{}, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MeterResponseDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given map[string]interface{} and assigns it to the Description field.
func (o *MeterResponseDto) SetDescription(v map[string]interface{}) {
	o.Description = v
}

// GetEventName returns the EventName field value
func (o *MeterResponseDto) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *MeterResponseDto) SetEventName(v string) {
	o.EventName = v
}

// GetAggregationType returns the AggregationType field value
func (o *MeterResponseDto) GetAggregationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AggregationType
}

// GetAggregationTypeOk returns a tuple with the AggregationType field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetAggregationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationType, true
}

// SetAggregationType sets field value
func (o *MeterResponseDto) SetAggregationType(v string) {
	o.AggregationType = v
}

// GetAggregationKey returns the AggregationKey field value if set, zero value otherwise.
func (o *MeterResponseDto) GetAggregationKey() map[string]interface{} {
	if o == nil || IsNil(o.AggregationKey) {
		var ret map[string]interface{}
		return ret
	}
	return o.AggregationKey
}

// GetAggregationKeyOk returns a tuple with the AggregationKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetAggregationKeyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AggregationKey) {
		return map[string]interface{}{}, false
	}
	return o.AggregationKey, true
}

// HasAggregationKey returns a boolean if a field has been set.
func (o *MeterResponseDto) HasAggregationKey() bool {
	if o != nil && !IsNil(o.AggregationKey) {
		return true
	}

	return false
}

// SetAggregationKey gets a reference to the given map[string]interface{} and assigns it to the AggregationKey field.
func (o *MeterResponseDto) SetAggregationKey(v map[string]interface{}) {
	o.AggregationKey = v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *MeterResponseDto) GetUnit() map[string]interface{} {
	if o == nil || IsNil(o.Unit) {
		var ret map[string]interface{}
		return ret
	}
	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetUnitOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Unit) {
		return map[string]interface{}{}, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *MeterResponseDto) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given map[string]interface{} and assigns it to the Unit field.
func (o *MeterResponseDto) SetUnit(v map[string]interface{}) {
	o.Unit = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *MeterResponseDto) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *MeterResponseDto) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *MeterResponseDto) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetArchived returns the Archived field value
func (o *MeterResponseDto) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *MeterResponseDto) SetArchived(v bool) {
	o.Archived = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MeterResponseDto) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MeterResponseDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *MeterResponseDto) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *MeterResponseDto) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *MeterResponseDto) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o MeterResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeterResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["businessId"] = o.BusinessId
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["eventName"] = o.EventName
	toSerialize["aggregationType"] = o.AggregationType
	if !IsNil(o.AggregationKey) {
		toSerialize["aggregationKey"] = o.AggregationKey
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["archived"] = o.Archived
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *MeterResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"businessId",
		"name",
		"eventName",
		"aggregationType",
		"archived",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeterResponseDto := _MeterResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeterResponseDto)

	if err != nil {
		return err
	}

	*o = MeterResponseDto(varMeterResponseDto)

	return err
}

type NullableMeterResponseDto struct {
	value *MeterResponseDto
	isSet bool
}

func (v NullableMeterResponseDto) Get() *MeterResponseDto {
	return v.value
}

func (v *NullableMeterResponseDto) Set(val *MeterResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMeterResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMeterResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeterResponseDto(val *MeterResponseDto) *NullableMeterResponseDto {
	return &NullableMeterResponseDto{value: val, isSet: true}
}

func (v NullableMeterResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeterResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


