/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevokeSeatDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeSeatDto{}

// RevokeSeatDto struct for RevokeSeatDto
type RevokeSeatDto struct {
	// The product ID of the addon (Whop Product ID or local ID).
	ProductId string `json:"productId"`
	// The number of seats to revoke/deduct.
	Quantity int32 `json:"quantity"`
}

type _RevokeSeatDto RevokeSeatDto

// NewRevokeSeatDto instantiates a new RevokeSeatDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeSeatDto(productId string, quantity int32) *RevokeSeatDto {
	this := RevokeSeatDto{}
	this.ProductId = productId
	this.Quantity = quantity
	return &this
}

// NewRevokeSeatDtoWithDefaults instantiates a new RevokeSeatDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeSeatDtoWithDefaults() *RevokeSeatDto {
	this := RevokeSeatDto{}
	return &this
}

// GetProductId returns the ProductId field value
func (o *RevokeSeatDto) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *RevokeSeatDto) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *RevokeSeatDto) SetProductId(v string) {
	o.ProductId = v
}

// GetQuantity returns the Quantity field value
func (o *RevokeSeatDto) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *RevokeSeatDto) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *RevokeSeatDto) SetQuantity(v int32) {
	o.Quantity = v
}

func (o RevokeSeatDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeSeatDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["productId"] = o.ProductId
	toSerialize["quantity"] = o.Quantity
	return toSerialize, nil
}

func (o *RevokeSeatDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productId",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevokeSeatDto := _RevokeSeatDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevokeSeatDto)

	if err != nil {
		return err
	}

	*o = RevokeSeatDto(varRevokeSeatDto)

	return err
}

type NullableRevokeSeatDto struct {
	value *RevokeSeatDto
	isSet bool
}

func (v NullableRevokeSeatDto) Get() *RevokeSeatDto {
	return v.value
}

func (v *NullableRevokeSeatDto) Set(val *RevokeSeatDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeSeatDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeSeatDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeSeatDto(val *RevokeSeatDto) *NullableRevokeSeatDto {
	return &NullableRevokeSeatDto{value: val, isSet: true}
}

func (v NullableRevokeSeatDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeSeatDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


