/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the DisputeEvidenceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeEvidenceDto{}

// DisputeEvidenceDto struct for DisputeEvidenceDto
type DisputeEvidenceDto struct {
	// Cancellation policy attachment ID
	CancellationPolicy NullableString `json:"cancellation_policy,omitempty"`
	// Customer communication attachment ID
	CustomerCommunication NullableString `json:"customer_communication,omitempty"`
	// Refund policy attachment ID
	RefundPolicy NullableString `json:"refund_policy,omitempty"`
	// Uncategorized attachment ID
	Uncategorized NullableString `json:"uncategorized,omitempty"`
}

// NewDisputeEvidenceDto instantiates a new DisputeEvidenceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisputeEvidenceDto() *DisputeEvidenceDto {
	this := DisputeEvidenceDto{}
	return &this
}

// NewDisputeEvidenceDtoWithDefaults instantiates a new DisputeEvidenceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisputeEvidenceDtoWithDefaults() *DisputeEvidenceDto {
	this := DisputeEvidenceDto{}
	return &this
}

// GetCancellationPolicy returns the CancellationPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DisputeEvidenceDto) GetCancellationPolicy() string {
	if o == nil || IsNil(o.CancellationPolicy.Get()) {
		var ret string
		return ret
	}
	return *o.CancellationPolicy.Get()
}

// GetCancellationPolicyOk returns a tuple with the CancellationPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DisputeEvidenceDto) GetCancellationPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancellationPolicy.Get(), o.CancellationPolicy.IsSet()
}

// HasCancellationPolicy returns a boolean if a field has been set.
func (o *DisputeEvidenceDto) HasCancellationPolicy() bool {
	if o != nil && o.CancellationPolicy.IsSet() {
		return true
	}

	return false
}

// SetCancellationPolicy gets a reference to the given NullableString and assigns it to the CancellationPolicy field.
func (o *DisputeEvidenceDto) SetCancellationPolicy(v string) {
	o.CancellationPolicy.Set(&v)
}
// SetCancellationPolicyNil sets the value for CancellationPolicy to be an explicit nil
func (o *DisputeEvidenceDto) SetCancellationPolicyNil() {
	o.CancellationPolicy.Set(nil)
}

// UnsetCancellationPolicy ensures that no value is present for CancellationPolicy, not even an explicit nil
func (o *DisputeEvidenceDto) UnsetCancellationPolicy() {
	o.CancellationPolicy.Unset()
}

// GetCustomerCommunication returns the CustomerCommunication field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DisputeEvidenceDto) GetCustomerCommunication() string {
	if o == nil || IsNil(o.CustomerCommunication.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerCommunication.Get()
}

// GetCustomerCommunicationOk returns a tuple with the CustomerCommunication field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DisputeEvidenceDto) GetCustomerCommunicationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerCommunication.Get(), o.CustomerCommunication.IsSet()
}

// HasCustomerCommunication returns a boolean if a field has been set.
func (o *DisputeEvidenceDto) HasCustomerCommunication() bool {
	if o != nil && o.CustomerCommunication.IsSet() {
		return true
	}

	return false
}

// SetCustomerCommunication gets a reference to the given NullableString and assigns it to the CustomerCommunication field.
func (o *DisputeEvidenceDto) SetCustomerCommunication(v string) {
	o.CustomerCommunication.Set(&v)
}
// SetCustomerCommunicationNil sets the value for CustomerCommunication to be an explicit nil
func (o *DisputeEvidenceDto) SetCustomerCommunicationNil() {
	o.CustomerCommunication.Set(nil)
}

// UnsetCustomerCommunication ensures that no value is present for CustomerCommunication, not even an explicit nil
func (o *DisputeEvidenceDto) UnsetCustomerCommunication() {
	o.CustomerCommunication.Unset()
}

// GetRefundPolicy returns the RefundPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DisputeEvidenceDto) GetRefundPolicy() string {
	if o == nil || IsNil(o.RefundPolicy.Get()) {
		var ret string
		return ret
	}
	return *o.RefundPolicy.Get()
}

// GetRefundPolicyOk returns a tuple with the RefundPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DisputeEvidenceDto) GetRefundPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RefundPolicy.Get(), o.RefundPolicy.IsSet()
}

// HasRefundPolicy returns a boolean if a field has been set.
func (o *DisputeEvidenceDto) HasRefundPolicy() bool {
	if o != nil && o.RefundPolicy.IsSet() {
		return true
	}

	return false
}

// SetRefundPolicy gets a reference to the given NullableString and assigns it to the RefundPolicy field.
func (o *DisputeEvidenceDto) SetRefundPolicy(v string) {
	o.RefundPolicy.Set(&v)
}
// SetRefundPolicyNil sets the value for RefundPolicy to be an explicit nil
func (o *DisputeEvidenceDto) SetRefundPolicyNil() {
	o.RefundPolicy.Set(nil)
}

// UnsetRefundPolicy ensures that no value is present for RefundPolicy, not even an explicit nil
func (o *DisputeEvidenceDto) UnsetRefundPolicy() {
	o.RefundPolicy.Unset()
}

// GetUncategorized returns the Uncategorized field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DisputeEvidenceDto) GetUncategorized() string {
	if o == nil || IsNil(o.Uncategorized.Get()) {
		var ret string
		return ret
	}
	return *o.Uncategorized.Get()
}

// GetUncategorizedOk returns a tuple with the Uncategorized field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DisputeEvidenceDto) GetUncategorizedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uncategorized.Get(), o.Uncategorized.IsSet()
}

// HasUncategorized returns a boolean if a field has been set.
func (o *DisputeEvidenceDto) HasUncategorized() bool {
	if o != nil && o.Uncategorized.IsSet() {
		return true
	}

	return false
}

// SetUncategorized gets a reference to the given NullableString and assigns it to the Uncategorized field.
func (o *DisputeEvidenceDto) SetUncategorized(v string) {
	o.Uncategorized.Set(&v)
}
// SetUncategorizedNil sets the value for Uncategorized to be an explicit nil
func (o *DisputeEvidenceDto) SetUncategorizedNil() {
	o.Uncategorized.Set(nil)
}

// UnsetUncategorized ensures that no value is present for Uncategorized, not even an explicit nil
func (o *DisputeEvidenceDto) UnsetUncategorized() {
	o.Uncategorized.Unset()
}

func (o DisputeEvidenceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisputeEvidenceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CancellationPolicy.IsSet() {
		toSerialize["cancellation_policy"] = o.CancellationPolicy.Get()
	}
	if o.CustomerCommunication.IsSet() {
		toSerialize["customer_communication"] = o.CustomerCommunication.Get()
	}
	if o.RefundPolicy.IsSet() {
		toSerialize["refund_policy"] = o.RefundPolicy.Get()
	}
	if o.Uncategorized.IsSet() {
		toSerialize["uncategorized"] = o.Uncategorized.Get()
	}
	return toSerialize, nil
}

type NullableDisputeEvidenceDto struct {
	value *DisputeEvidenceDto
	isSet bool
}

func (v NullableDisputeEvidenceDto) Get() *DisputeEvidenceDto {
	return v.value
}

func (v *NullableDisputeEvidenceDto) Set(val *DisputeEvidenceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeEvidenceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeEvidenceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeEvidenceDto(val *DisputeEvidenceDto) *NullableDisputeEvidenceDto {
	return &NullableDisputeEvidenceDto{value: val, isSet: true}
}

func (v NullableDisputeEvidenceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeEvidenceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


