/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomerListResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerListResponseDto{}

// CustomerListResponseDto struct for CustomerListResponseDto
type CustomerListResponseDto struct {
	// List of customers
	Items []CustomerResponseDto `json:"items"`
	// Total count of customers matching the filters
	TotalCount float32 `json:"total_count"`
}

type _CustomerListResponseDto CustomerListResponseDto

// NewCustomerListResponseDto instantiates a new CustomerListResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerListResponseDto(items []CustomerResponseDto, totalCount float32) *CustomerListResponseDto {
	this := CustomerListResponseDto{}
	this.Items = items
	this.TotalCount = totalCount
	return &this
}

// NewCustomerListResponseDtoWithDefaults instantiates a new CustomerListResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerListResponseDtoWithDefaults() *CustomerListResponseDto {
	this := CustomerListResponseDto{}
	return &this
}

// GetItems returns the Items field value
func (o *CustomerListResponseDto) GetItems() []CustomerResponseDto {
	if o == nil {
		var ret []CustomerResponseDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CustomerListResponseDto) GetItemsOk() ([]CustomerResponseDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CustomerListResponseDto) SetItems(v []CustomerResponseDto) {
	o.Items = v
}

// GetTotalCount returns the TotalCount field value
func (o *CustomerListResponseDto) GetTotalCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *CustomerListResponseDto) GetTotalCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *CustomerListResponseDto) SetTotalCount(v float32) {
	o.TotalCount = v
}

func (o CustomerListResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerListResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total_count"] = o.TotalCount
	return toSerialize, nil
}

func (o *CustomerListResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerListResponseDto := _CustomerListResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerListResponseDto)

	if err != nil {
		return err
	}

	*o = CustomerListResponseDto(varCustomerListResponseDto)

	return err
}

type NullableCustomerListResponseDto struct {
	value *CustomerListResponseDto
	isSet bool
}

func (v NullableCustomerListResponseDto) Get() *CustomerListResponseDto {
	return v.value
}

func (v *NullableCustomerListResponseDto) Set(val *CustomerListResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerListResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerListResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerListResponseDto(val *CustomerListResponseDto) *NullableCustomerListResponseDto {
	return &NullableCustomerListResponseDto{value: val, isSet: true}
}

func (v NullableCustomerListResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerListResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


