/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
)

// checks if the WebhookRefundPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookRefundPayload{}

// WebhookRefundPayload struct for WebhookRefundPayload
type WebhookRefundPayload struct {
	// Internal refund ID.
	Id *string `json:"id,omitempty"`
	PaymentId *string `json:"paymentId,omitempty"`
	// Dollar value, 2 d.p.
	Amount *string `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Status *string `json:"status,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	ReferenceValue NullableString `json:"referenceValue,omitempty"`
	Provider NullableString `json:"provider,omitempty"`
	ProviderCreatedAt NullableTime `json:"providerCreatedAt,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewWebhookRefundPayload instantiates a new WebhookRefundPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookRefundPayload() *WebhookRefundPayload {
	this := WebhookRefundPayload{}
	return &this
}

// NewWebhookRefundPayloadWithDefaults instantiates a new WebhookRefundPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookRefundPayloadWithDefaults() *WebhookRefundPayload {
	this := WebhookRefundPayload{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebhookRefundPayload) SetId(v string) {
	o.Id = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId) {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetPaymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *WebhookRefundPayload) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *WebhookRefundPayload) SetAmount(v string) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *WebhookRefundPayload) SetCurrency(v string) {
	o.Currency = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WebhookRefundPayload) SetStatus(v string) {
	o.Status = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookRefundPayload) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookRefundPayload) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *WebhookRefundPayload) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *WebhookRefundPayload) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *WebhookRefundPayload) UnsetReason() {
	o.Reason.Unset()
}

// GetReferenceValue returns the ReferenceValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookRefundPayload) GetReferenceValue() string {
	if o == nil || IsNil(o.ReferenceValue.Get()) {
		var ret string
		return ret
	}
	return *o.ReferenceValue.Get()
}

// GetReferenceValueOk returns a tuple with the ReferenceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookRefundPayload) GetReferenceValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceValue.Get(), o.ReferenceValue.IsSet()
}

// HasReferenceValue returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasReferenceValue() bool {
	if o != nil && o.ReferenceValue.IsSet() {
		return true
	}

	return false
}

// SetReferenceValue gets a reference to the given NullableString and assigns it to the ReferenceValue field.
func (o *WebhookRefundPayload) SetReferenceValue(v string) {
	o.ReferenceValue.Set(&v)
}
// SetReferenceValueNil sets the value for ReferenceValue to be an explicit nil
func (o *WebhookRefundPayload) SetReferenceValueNil() {
	o.ReferenceValue.Set(nil)
}

// UnsetReferenceValue ensures that no value is present for ReferenceValue, not even an explicit nil
func (o *WebhookRefundPayload) UnsetReferenceValue() {
	o.ReferenceValue.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookRefundPayload) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookRefundPayload) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *WebhookRefundPayload) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *WebhookRefundPayload) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *WebhookRefundPayload) UnsetProvider() {
	o.Provider.Unset()
}

// GetProviderCreatedAt returns the ProviderCreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookRefundPayload) GetProviderCreatedAt() time.Time {
	if o == nil || IsNil(o.ProviderCreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ProviderCreatedAt.Get()
}

// GetProviderCreatedAtOk returns a tuple with the ProviderCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookRefundPayload) GetProviderCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderCreatedAt.Get(), o.ProviderCreatedAt.IsSet()
}

// HasProviderCreatedAt returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasProviderCreatedAt() bool {
	if o != nil && o.ProviderCreatedAt.IsSet() {
		return true
	}

	return false
}

// SetProviderCreatedAt gets a reference to the given NullableTime and assigns it to the ProviderCreatedAt field.
func (o *WebhookRefundPayload) SetProviderCreatedAt(v time.Time) {
	o.ProviderCreatedAt.Set(&v)
}
// SetProviderCreatedAtNil sets the value for ProviderCreatedAt to be an explicit nil
func (o *WebhookRefundPayload) SetProviderCreatedAtNil() {
	o.ProviderCreatedAt.Set(nil)
}

// UnsetProviderCreatedAt ensures that no value is present for ProviderCreatedAt, not even an explicit nil
func (o *WebhookRefundPayload) UnsetProviderCreatedAt() {
	o.ProviderCreatedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WebhookRefundPayload) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WebhookRefundPayload) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRefundPayload) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WebhookRefundPayload) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WebhookRefundPayload) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o WebhookRefundPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookRefundPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PaymentId) {
		toSerialize["paymentId"] = o.PaymentId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.ReferenceValue.IsSet() {
		toSerialize["referenceValue"] = o.ReferenceValue.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.ProviderCreatedAt.IsSet() {
		toSerialize["providerCreatedAt"] = o.ProviderCreatedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableWebhookRefundPayload struct {
	value *WebhookRefundPayload
	isSet bool
}

func (v NullableWebhookRefundPayload) Get() *WebhookRefundPayload {
	return v.value
}

func (v *NullableWebhookRefundPayload) Set(val *WebhookRefundPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookRefundPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookRefundPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookRefundPayload(val *WebhookRefundPayload) *NullableWebhookRefundPayload {
	return &NullableWebhookRefundPayload{value: val, isSet: true}
}

func (v NullableWebhookRefundPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookRefundPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


