/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCheckoutLinkDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCheckoutLinkDto{}

// CreateCheckoutLinkDto struct for CreateCheckoutLinkDto
type CreateCheckoutLinkDto struct {
	// The friendly display title of this checkout link
	Title *string `json:"title,omitempty"`
	// Product database/Whop ID to sell
	ProductId string `json:"productId"`
	// Optional collection database ID to sell
	CollectionId *string `json:"collectionId,omitempty"`
	// Prefilled customer name for checkout inputs
	CustomerName *string `json:"customerName,omitempty"`
	// Prefilled customer email for checkout inputs
	CustomerEmail *string `json:"customerEmail,omitempty"`
	// Prefilled customer billing address line 1
	AddressLine1 *string `json:"addressLine1,omitempty"`
	// Prefilled customer billing city
	City *string `json:"city,omitempty"`
	// Prefilled customer billing state
	State *string `json:"state,omitempty"`
	// Prefilled customer billing zip/postal code
	PostalCode *string `json:"postalCode,omitempty"`
	// Prefilled customer billing country (2-letter ISO)
	Country *string `json:"country,omitempty"`
	// Override quantity for checkout session
	Quantity map[string]interface{} `json:"quantity,omitempty"`
	// The absolute URL to redirect to upon successful payment completion
	RedirectUrl *string `json:"redirectUrl,omitempty"`
	// The absolute URL to redirect to if a customer cancels the payment
	CancelUrl *string `json:"cancelUrl,omitempty"`
	// Whether to display discount input form fields on checkout screen
	ShowDiscounts *bool `json:"showDiscounts,omitempty"`
}

type _CreateCheckoutLinkDto CreateCheckoutLinkDto

// NewCreateCheckoutLinkDto instantiates a new CreateCheckoutLinkDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCheckoutLinkDto(productId string) *CreateCheckoutLinkDto {
	this := CreateCheckoutLinkDto{}
	this.ProductId = productId
	var showDiscounts bool = true
	this.ShowDiscounts = &showDiscounts
	return &this
}

// NewCreateCheckoutLinkDtoWithDefaults instantiates a new CreateCheckoutLinkDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCheckoutLinkDtoWithDefaults() *CreateCheckoutLinkDto {
	this := CreateCheckoutLinkDto{}
	var showDiscounts bool = true
	this.ShowDiscounts = &showDiscounts
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateCheckoutLinkDto) SetTitle(v string) {
	o.Title = &v
}

// GetProductId returns the ProductId field value
func (o *CreateCheckoutLinkDto) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *CreateCheckoutLinkDto) SetProductId(v string) {
	o.ProductId = v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCollectionId() string {
	if o == nil || IsNil(o.CollectionId) {
		var ret string
		return ret
	}
	return *o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionId) {
		return nil, false
	}
	return o.CollectionId, true
}

// HasCollectionId returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCollectionId() bool {
	if o != nil && !IsNil(o.CollectionId) {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given string and assigns it to the CollectionId field.
func (o *CreateCheckoutLinkDto) SetCollectionId(v string) {
	o.CollectionId = &v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *CreateCheckoutLinkDto) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail) {
		var ret string
		return ret
	}
	return *o.CustomerEmail
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCustomerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerEmail) {
		return nil, false
	}
	return o.CustomerEmail, true
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCustomerEmail() bool {
	if o != nil && !IsNil(o.CustomerEmail) {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given string and assigns it to the CustomerEmail field.
func (o *CreateCheckoutLinkDto) SetCustomerEmail(v string) {
	o.CustomerEmail = &v
}

// GetAddressLine1 returns the AddressLine1 field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetAddressLine1() string {
	if o == nil || IsNil(o.AddressLine1) {
		var ret string
		return ret
	}
	return *o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetAddressLine1Ok() (*string, bool) {
	if o == nil || IsNil(o.AddressLine1) {
		return nil, false
	}
	return o.AddressLine1, true
}

// HasAddressLine1 returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasAddressLine1() bool {
	if o != nil && !IsNil(o.AddressLine1) {
		return true
	}

	return false
}

// SetAddressLine1 gets a reference to the given string and assigns it to the AddressLine1 field.
func (o *CreateCheckoutLinkDto) SetAddressLine1(v string) {
	o.AddressLine1 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *CreateCheckoutLinkDto) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *CreateCheckoutLinkDto) SetState(v string) {
	o.State = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *CreateCheckoutLinkDto) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CreateCheckoutLinkDto) SetCountry(v string) {
	o.Country = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetQuantity() map[string]interface{} {
	if o == nil || IsNil(o.Quantity) {
		var ret map[string]interface{}
		return ret
	}
	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetQuantityOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Quantity) {
		return map[string]interface{}{}, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given map[string]interface{} and assigns it to the Quantity field.
func (o *CreateCheckoutLinkDto) SetQuantity(v map[string]interface{}) {
	o.Quantity = v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetRedirectUrl() string {
	if o == nil || IsNil(o.RedirectUrl) {
		var ret string
		return ret
	}
	return *o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return o.RedirectUrl, true
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasRedirectUrl() bool {
	if o != nil && !IsNil(o.RedirectUrl) {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given string and assigns it to the RedirectUrl field.
func (o *CreateCheckoutLinkDto) SetRedirectUrl(v string) {
	o.RedirectUrl = &v
}

// GetCancelUrl returns the CancelUrl field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetCancelUrl() string {
	if o == nil || IsNil(o.CancelUrl) {
		var ret string
		return ret
	}
	return *o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetCancelUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CancelUrl) {
		return nil, false
	}
	return o.CancelUrl, true
}

// HasCancelUrl returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasCancelUrl() bool {
	if o != nil && !IsNil(o.CancelUrl) {
		return true
	}

	return false
}

// SetCancelUrl gets a reference to the given string and assigns it to the CancelUrl field.
func (o *CreateCheckoutLinkDto) SetCancelUrl(v string) {
	o.CancelUrl = &v
}

// GetShowDiscounts returns the ShowDiscounts field value if set, zero value otherwise.
func (o *CreateCheckoutLinkDto) GetShowDiscounts() bool {
	if o == nil || IsNil(o.ShowDiscounts) {
		var ret bool
		return ret
	}
	return *o.ShowDiscounts
}

// GetShowDiscountsOk returns a tuple with the ShowDiscounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutLinkDto) GetShowDiscountsOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowDiscounts) {
		return nil, false
	}
	return o.ShowDiscounts, true
}

// HasShowDiscounts returns a boolean if a field has been set.
func (o *CreateCheckoutLinkDto) HasShowDiscounts() bool {
	if o != nil && !IsNil(o.ShowDiscounts) {
		return true
	}

	return false
}

// SetShowDiscounts gets a reference to the given bool and assigns it to the ShowDiscounts field.
func (o *CreateCheckoutLinkDto) SetShowDiscounts(v bool) {
	o.ShowDiscounts = &v
}

func (o CreateCheckoutLinkDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCheckoutLinkDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	toSerialize["productId"] = o.ProductId
	if !IsNil(o.CollectionId) {
		toSerialize["collectionId"] = o.CollectionId
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.CustomerEmail) {
		toSerialize["customerEmail"] = o.CustomerEmail
	}
	if !IsNil(o.AddressLine1) {
		toSerialize["addressLine1"] = o.AddressLine1
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.RedirectUrl) {
		toSerialize["redirectUrl"] = o.RedirectUrl
	}
	if !IsNil(o.CancelUrl) {
		toSerialize["cancelUrl"] = o.CancelUrl
	}
	if !IsNil(o.ShowDiscounts) {
		toSerialize["showDiscounts"] = o.ShowDiscounts
	}
	return toSerialize, nil
}

func (o *CreateCheckoutLinkDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCheckoutLinkDto := _CreateCheckoutLinkDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCheckoutLinkDto)

	if err != nil {
		return err
	}

	*o = CreateCheckoutLinkDto(varCreateCheckoutLinkDto)

	return err
}

type NullableCreateCheckoutLinkDto struct {
	value *CreateCheckoutLinkDto
	isSet bool
}

func (v NullableCreateCheckoutLinkDto) Get() *CreateCheckoutLinkDto {
	return v.value
}

func (v *NullableCreateCheckoutLinkDto) Set(val *CreateCheckoutLinkDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCheckoutLinkDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCheckoutLinkDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCheckoutLinkDto(val *CreateCheckoutLinkDto) *NullableCreateCheckoutLinkDto {
	return &NullableCreateCheckoutLinkDto{value: val, isSet: true}
}

func (v NullableCreateCheckoutLinkDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCheckoutLinkDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


