/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Order type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Order{}

// Order Represents an order (payment) processed under your business, containing customer, billing, product cart, and refund details.
type Order struct {
	// Unique internal database identifier.
	Id string `json:"id"`
	// The invoice print URL.
	InvoiceUrl string `json:"invoice_url"`
	// Customer details.
	Customer OrderCustomer `json:"customer"`
	// Total paid amount in cents.
	TotalAmount int32 `json:"total_amount"`
	// Subtotal amount in cents.
	Subtotal int32 `json:"subtotal"`
	// Total paid amount converted to USD.
	UsdTotal *float32 `json:"usdTotal,omitempty"`
	// Tax amount in cents.
	TaxAmount int32 `json:"tax_amount"`
	// Application fee in cents.
	ApplicationFee int32 `json:"application_fee"`
	// Net amount after fees in cents.
	AmountAfterFees int32 `json:"amount_after_fees"`
	// Currency code.
	Currency string `json:"currency"`
	// Current status of the payment.
	Status string `json:"status"`
	// Payment creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Payment completion/paid timestamp.
	PaidAt *time.Time `json:"paidAt,omitempty"`
	// Payment method utilized.
	PaymentMethod string `json:"payment_method"`
	// Last four digits of card used.
	CardLastFour *string `json:"card_last_four,omitempty"`
	// Card network/brand.
	CardNetwork *string `json:"card_network,omitempty"`
	// Card type.
	CardType *string `json:"card_type,omitempty"`
	// Billing address details.
	Billing *OrderBilling `json:"billing,omitempty"`
	// Products purchased in this order.
	ProductCart []OrderProductCart `json:"product_cart"`
	// Custom metadata payload associated with this payment.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Order details snapshot.
	Order *OrderDetail `json:"order,omitempty"`
	// Indicates whether the order is eligible for refund.
	Refundable bool `json:"refundable"`
	// List of refunds associated with this payment.
	Refunds []OrderRefund `json:"refunds,omitempty"`
	// Business unique ID identifier.
	BusinessId string `json:"businessId"`
	// Business display title/name.
	BusinessName string `json:"businessName"`
	// Billing reason detail.
	BillingReason *string `json:"billing_reason,omitempty"`
}

type _Order Order

// NewOrder instantiates a new Order object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrder(id string, invoiceUrl string, customer OrderCustomer, totalAmount int32, subtotal int32, taxAmount int32, applicationFee int32, amountAfterFees int32, currency string, status string, createdAt time.Time, paymentMethod string, productCart []OrderProductCart, refundable bool, businessId string, businessName string) *Order {
	this := Order{}
	this.Id = id
	this.InvoiceUrl = invoiceUrl
	this.Customer = customer
	this.TotalAmount = totalAmount
	this.Subtotal = subtotal
	this.TaxAmount = taxAmount
	this.ApplicationFee = applicationFee
	this.AmountAfterFees = amountAfterFees
	this.Currency = currency
	this.Status = status
	this.CreatedAt = createdAt
	this.PaymentMethod = paymentMethod
	this.ProductCart = productCart
	this.Refundable = refundable
	this.BusinessId = businessId
	this.BusinessName = businessName
	return &this
}

// NewOrderWithDefaults instantiates a new Order object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderWithDefaults() *Order {
	this := Order{}
	return &this
}

// GetId returns the Id field value
func (o *Order) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Order) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Order) SetId(v string) {
	o.Id = v
}

// GetInvoiceUrl returns the InvoiceUrl field value
func (o *Order) GetInvoiceUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceUrl
}

// GetInvoiceUrlOk returns a tuple with the InvoiceUrl field value
// and a boolean to check if the value has been set.
func (o *Order) GetInvoiceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceUrl, true
}

// SetInvoiceUrl sets field value
func (o *Order) SetInvoiceUrl(v string) {
	o.InvoiceUrl = v
}

// GetCustomer returns the Customer field value
func (o *Order) GetCustomer() OrderCustomer {
	if o == nil {
		var ret OrderCustomer
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *Order) GetCustomerOk() (*OrderCustomer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *Order) SetCustomer(v OrderCustomer) {
	o.Customer = v
}

// GetTotalAmount returns the TotalAmount field value
func (o *Order) GetTotalAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value
// and a boolean to check if the value has been set.
func (o *Order) GetTotalAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAmount, true
}

// SetTotalAmount sets field value
func (o *Order) SetTotalAmount(v int32) {
	o.TotalAmount = v
}

// GetSubtotal returns the Subtotal field value
func (o *Order) GetSubtotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value
// and a boolean to check if the value has been set.
func (o *Order) GetSubtotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subtotal, true
}

// SetSubtotal sets field value
func (o *Order) SetSubtotal(v int32) {
	o.Subtotal = v
}

// GetUsdTotal returns the UsdTotal field value if set, zero value otherwise.
func (o *Order) GetUsdTotal() float32 {
	if o == nil || IsNil(o.UsdTotal) {
		var ret float32
		return ret
	}
	return *o.UsdTotal
}

// GetUsdTotalOk returns a tuple with the UsdTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetUsdTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.UsdTotal) {
		return nil, false
	}
	return o.UsdTotal, true
}

// HasUsdTotal returns a boolean if a field has been set.
func (o *Order) HasUsdTotal() bool {
	if o != nil && !IsNil(o.UsdTotal) {
		return true
	}

	return false
}

// SetUsdTotal gets a reference to the given float32 and assigns it to the UsdTotal field.
func (o *Order) SetUsdTotal(v float32) {
	o.UsdTotal = &v
}

// GetTaxAmount returns the TaxAmount field value
func (o *Order) GetTaxAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value
// and a boolean to check if the value has been set.
func (o *Order) GetTaxAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxAmount, true
}

// SetTaxAmount sets field value
func (o *Order) SetTaxAmount(v int32) {
	o.TaxAmount = v
}

// GetApplicationFee returns the ApplicationFee field value
func (o *Order) GetApplicationFee() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApplicationFee
}

// GetApplicationFeeOk returns a tuple with the ApplicationFee field value
// and a boolean to check if the value has been set.
func (o *Order) GetApplicationFeeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationFee, true
}

// SetApplicationFee sets field value
func (o *Order) SetApplicationFee(v int32) {
	o.ApplicationFee = v
}

// GetAmountAfterFees returns the AmountAfterFees field value
func (o *Order) GetAmountAfterFees() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmountAfterFees
}

// GetAmountAfterFeesOk returns a tuple with the AmountAfterFees field value
// and a boolean to check if the value has been set.
func (o *Order) GetAmountAfterFeesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountAfterFees, true
}

// SetAmountAfterFees sets field value
func (o *Order) SetAmountAfterFees(v int32) {
	o.AmountAfterFees = v
}

// GetCurrency returns the Currency field value
func (o *Order) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *Order) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *Order) SetCurrency(v string) {
	o.Currency = v
}

// GetStatus returns the Status field value
func (o *Order) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Order) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Order) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Order) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Order) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Order) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise.
func (o *Order) GetPaidAt() time.Time {
	if o == nil || IsNil(o.PaidAt) {
		var ret time.Time
		return ret
	}
	return *o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetPaidAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PaidAt) {
		return nil, false
	}
	return o.PaidAt, true
}

// HasPaidAt returns a boolean if a field has been set.
func (o *Order) HasPaidAt() bool {
	if o != nil && !IsNil(o.PaidAt) {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given time.Time and assigns it to the PaidAt field.
func (o *Order) SetPaidAt(v time.Time) {
	o.PaidAt = &v
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *Order) GetPaymentMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *Order) GetPaymentMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *Order) SetPaymentMethod(v string) {
	o.PaymentMethod = v
}

// GetCardLastFour returns the CardLastFour field value if set, zero value otherwise.
func (o *Order) GetCardLastFour() string {
	if o == nil || IsNil(o.CardLastFour) {
		var ret string
		return ret
	}
	return *o.CardLastFour
}

// GetCardLastFourOk returns a tuple with the CardLastFour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetCardLastFourOk() (*string, bool) {
	if o == nil || IsNil(o.CardLastFour) {
		return nil, false
	}
	return o.CardLastFour, true
}

// HasCardLastFour returns a boolean if a field has been set.
func (o *Order) HasCardLastFour() bool {
	if o != nil && !IsNil(o.CardLastFour) {
		return true
	}

	return false
}

// SetCardLastFour gets a reference to the given string and assigns it to the CardLastFour field.
func (o *Order) SetCardLastFour(v string) {
	o.CardLastFour = &v
}

// GetCardNetwork returns the CardNetwork field value if set, zero value otherwise.
func (o *Order) GetCardNetwork() string {
	if o == nil || IsNil(o.CardNetwork) {
		var ret string
		return ret
	}
	return *o.CardNetwork
}

// GetCardNetworkOk returns a tuple with the CardNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetCardNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.CardNetwork) {
		return nil, false
	}
	return o.CardNetwork, true
}

// HasCardNetwork returns a boolean if a field has been set.
func (o *Order) HasCardNetwork() bool {
	if o != nil && !IsNil(o.CardNetwork) {
		return true
	}

	return false
}

// SetCardNetwork gets a reference to the given string and assigns it to the CardNetwork field.
func (o *Order) SetCardNetwork(v string) {
	o.CardNetwork = &v
}

// GetCardType returns the CardType field value if set, zero value otherwise.
func (o *Order) GetCardType() string {
	if o == nil || IsNil(o.CardType) {
		var ret string
		return ret
	}
	return *o.CardType
}

// GetCardTypeOk returns a tuple with the CardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetCardTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CardType) {
		return nil, false
	}
	return o.CardType, true
}

// HasCardType returns a boolean if a field has been set.
func (o *Order) HasCardType() bool {
	if o != nil && !IsNil(o.CardType) {
		return true
	}

	return false
}

// SetCardType gets a reference to the given string and assigns it to the CardType field.
func (o *Order) SetCardType(v string) {
	o.CardType = &v
}

// GetBilling returns the Billing field value if set, zero value otherwise.
func (o *Order) GetBilling() OrderBilling {
	if o == nil || IsNil(o.Billing) {
		var ret OrderBilling
		return ret
	}
	return *o.Billing
}

// GetBillingOk returns a tuple with the Billing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetBillingOk() (*OrderBilling, bool) {
	if o == nil || IsNil(o.Billing) {
		return nil, false
	}
	return o.Billing, true
}

// HasBilling returns a boolean if a field has been set.
func (o *Order) HasBilling() bool {
	if o != nil && !IsNil(o.Billing) {
		return true
	}

	return false
}

// SetBilling gets a reference to the given OrderBilling and assigns it to the Billing field.
func (o *Order) SetBilling(v OrderBilling) {
	o.Billing = &v
}

// GetProductCart returns the ProductCart field value
func (o *Order) GetProductCart() []OrderProductCart {
	if o == nil {
		var ret []OrderProductCart
		return ret
	}

	return o.ProductCart
}

// GetProductCartOk returns a tuple with the ProductCart field value
// and a boolean to check if the value has been set.
func (o *Order) GetProductCartOk() ([]OrderProductCart, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductCart, true
}

// SetProductCart sets field value
func (o *Order) SetProductCart(v []OrderProductCart) {
	o.ProductCart = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Order) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Order) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Order) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Order) GetOrder() OrderDetail {
	if o == nil || IsNil(o.Order) {
		var ret OrderDetail
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetOrderOk() (*OrderDetail, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Order) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given OrderDetail and assigns it to the Order field.
func (o *Order) SetOrder(v OrderDetail) {
	o.Order = &v
}

// GetRefundable returns the Refundable field value
func (o *Order) GetRefundable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Refundable
}

// GetRefundableOk returns a tuple with the Refundable field value
// and a boolean to check if the value has been set.
func (o *Order) GetRefundableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refundable, true
}

// SetRefundable sets field value
func (o *Order) SetRefundable(v bool) {
	o.Refundable = v
}

// GetRefunds returns the Refunds field value if set, zero value otherwise.
func (o *Order) GetRefunds() []OrderRefund {
	if o == nil || IsNil(o.Refunds) {
		var ret []OrderRefund
		return ret
	}
	return o.Refunds
}

// GetRefundsOk returns a tuple with the Refunds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetRefundsOk() ([]OrderRefund, bool) {
	if o == nil || IsNil(o.Refunds) {
		return nil, false
	}
	return o.Refunds, true
}

// HasRefunds returns a boolean if a field has been set.
func (o *Order) HasRefunds() bool {
	if o != nil && !IsNil(o.Refunds) {
		return true
	}

	return false
}

// SetRefunds gets a reference to the given []OrderRefund and assigns it to the Refunds field.
func (o *Order) SetRefunds(v []OrderRefund) {
	o.Refunds = v
}

// GetBusinessId returns the BusinessId field value
func (o *Order) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *Order) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *Order) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetBusinessName returns the BusinessName field value
func (o *Order) GetBusinessName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessName
}

// GetBusinessNameOk returns a tuple with the BusinessName field value
// and a boolean to check if the value has been set.
func (o *Order) GetBusinessNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessName, true
}

// SetBusinessName sets field value
func (o *Order) SetBusinessName(v string) {
	o.BusinessName = v
}

// GetBillingReason returns the BillingReason field value if set, zero value otherwise.
func (o *Order) GetBillingReason() string {
	if o == nil || IsNil(o.BillingReason) {
		var ret string
		return ret
	}
	return *o.BillingReason
}

// GetBillingReasonOk returns a tuple with the BillingReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetBillingReasonOk() (*string, bool) {
	if o == nil || IsNil(o.BillingReason) {
		return nil, false
	}
	return o.BillingReason, true
}

// HasBillingReason returns a boolean if a field has been set.
func (o *Order) HasBillingReason() bool {
	if o != nil && !IsNil(o.BillingReason) {
		return true
	}

	return false
}

// SetBillingReason gets a reference to the given string and assigns it to the BillingReason field.
func (o *Order) SetBillingReason(v string) {
	o.BillingReason = &v
}

func (o Order) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Order) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["invoice_url"] = o.InvoiceUrl
	toSerialize["customer"] = o.Customer
	toSerialize["total_amount"] = o.TotalAmount
	toSerialize["subtotal"] = o.Subtotal
	if !IsNil(o.UsdTotal) {
		toSerialize["usdTotal"] = o.UsdTotal
	}
	toSerialize["tax_amount"] = o.TaxAmount
	toSerialize["application_fee"] = o.ApplicationFee
	toSerialize["amount_after_fees"] = o.AmountAfterFees
	toSerialize["currency"] = o.Currency
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.PaidAt) {
		toSerialize["paidAt"] = o.PaidAt
	}
	toSerialize["payment_method"] = o.PaymentMethod
	if !IsNil(o.CardLastFour) {
		toSerialize["card_last_four"] = o.CardLastFour
	}
	if !IsNil(o.CardNetwork) {
		toSerialize["card_network"] = o.CardNetwork
	}
	if !IsNil(o.CardType) {
		toSerialize["card_type"] = o.CardType
	}
	if !IsNil(o.Billing) {
		toSerialize["billing"] = o.Billing
	}
	toSerialize["product_cart"] = o.ProductCart
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	toSerialize["refundable"] = o.Refundable
	if !IsNil(o.Refunds) {
		toSerialize["refunds"] = o.Refunds
	}
	toSerialize["businessId"] = o.BusinessId
	toSerialize["businessName"] = o.BusinessName
	if !IsNil(o.BillingReason) {
		toSerialize["billing_reason"] = o.BillingReason
	}
	return toSerialize, nil
}

func (o *Order) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"invoice_url",
		"customer",
		"total_amount",
		"subtotal",
		"tax_amount",
		"application_fee",
		"amount_after_fees",
		"currency",
		"status",
		"created_at",
		"payment_method",
		"product_cart",
		"refundable",
		"businessId",
		"businessName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrder := _Order{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrder)

	if err != nil {
		return err
	}

	*o = Order(varOrder)

	return err
}

type NullableOrder struct {
	value *Order
	isSet bool
}

func (v NullableOrder) Get() *Order {
	return v.value
}

func (v *NullableOrder) Set(val *Order) {
	v.value = val
	v.isSet = true
}

func (v NullableOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrder(val *Order) *NullableOrder {
	return &NullableOrder{value: val, isSet: true}
}

func (v NullableOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


