/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCollectionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCollectionDto{}

// CreateCollectionDto struct for CreateCollectionDto
type CreateCollectionDto struct {
	// The friendly name of the collection
	Name string `json:"name"`
	// A detailed description of this collection
	Description *string `json:"description,omitempty"`
	// The display cover image URL for this collection
	ImageUrl *string `json:"imageUrl,omitempty"`
	// The collection status
	Status *string `json:"status,omitempty"`
	// List of products to include in this collection. At least one product is required.
	Products []CollectionProductEntry `json:"products"`
}

type _CreateCollectionDto CreateCollectionDto

// NewCreateCollectionDto instantiates a new CreateCollectionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCollectionDto(name string, products []CollectionProductEntry) *CreateCollectionDto {
	this := CreateCollectionDto{}
	this.Name = name
	this.Products = products
	return &this
}

// NewCreateCollectionDtoWithDefaults instantiates a new CreateCollectionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCollectionDtoWithDefaults() *CreateCollectionDto {
	this := CreateCollectionDto{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCollectionDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCollectionDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateCollectionDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollectionDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateCollectionDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateCollectionDto) SetDescription(v string) {
	o.Description = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *CreateCollectionDto) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollectionDto) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *CreateCollectionDto) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *CreateCollectionDto) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateCollectionDto) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollectionDto) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateCollectionDto) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateCollectionDto) SetStatus(v string) {
	o.Status = &v
}

// GetProducts returns the Products field value
func (o *CreateCollectionDto) GetProducts() []CollectionProductEntry {
	if o == nil {
		var ret []CollectionProductEntry
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionDto) GetProductsOk() ([]CollectionProductEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *CreateCollectionDto) SetProducts(v []CollectionProductEntry) {
	o.Products = v
}

func (o CreateCollectionDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCollectionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

func (o *CreateCollectionDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"products",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCollectionDto := _CreateCollectionDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCollectionDto)

	if err != nil {
		return err
	}

	*o = CreateCollectionDto(varCreateCollectionDto)

	return err
}

type NullableCreateCollectionDto struct {
	value *CreateCollectionDto
	isSet bool
}

func (v NullableCreateCollectionDto) Get() *CreateCollectionDto {
	return v.value
}

func (v *NullableCreateCollectionDto) Set(val *CreateCollectionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCollectionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCollectionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCollectionDto(val *CreateCollectionDto) *NullableCreateCollectionDto {
	return &NullableCreateCollectionDto{value: val, isSet: true}
}

func (v NullableCreateCollectionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCollectionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


