/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the License type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &License{}

// License Represents a cryptographically secure software license key issued to a customer upon purchase or manual issuance.
type License struct {
	// The unique prefix-based identifier of the license key.
	Id string `json:"id"`
	// The cryptographically generated license key string delivered to the customer.
	Key string `json:"key"`
	// Lifecycle status of the license. ACTIVE = active. DISABLED = suspended. REVOKED = hard-revoked.
	Status string `json:"status"`
	// The unique identifier associated with the business this license belongs to.
	BusinessId string `json:"businessId"`
	// The unique ID of the product this license key is associated with.
	ProductId NullableString `json:"productId"`
	// The unique payment identifier that triggered the issuance of this license key.
	PaymentId NullableString `json:"paymentId"`
	// The unique customer identifier (ID) who received this license key.
	CustomerId NullableString `json:"customerId"`
	// Maximum number of simultaneous active device instances allowed for this license. Null means unlimited.
	ActivationLimit NullableFloat32 `json:"activationLimit"`
	// Optional message displayed to the customer upon successful activation.
	ActivationMessage NullableString `json:"activationMessage"`
	// Running count of how many times this license key has been activated.
	InstancesCount float32 `json:"instancesCount"`
	// Relative expiry duration in hours from the time of issuance.
	ExpiryHours NullableFloat32 `json:"expiryHours"`
	// Absolute expiration timestamp. The license becomes invalid after this point.
	ExpiresAt NullableString `json:"expiresAt"`
	// Optional custom metadata filters associated with the license.
	Filters map[string]interface{} `json:"filters"`
	// Indicates if the license key is archived.
	Archived bool `json:"archived"`
	// Timestamp indicating exactly when the license key was issued.
	CreatedAt string `json:"createdAt"`
	// Timestamp indicating when the license key was last modified.
	UpdatedAt string `json:"updatedAt"`
}

type _License License

// NewLicense instantiates a new License object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicense(id string, key string, status string, businessId string, productId NullableString, paymentId NullableString, customerId NullableString, activationLimit NullableFloat32, activationMessage NullableString, instancesCount float32, expiryHours NullableFloat32, expiresAt NullableString, filters map[string]interface{}, archived bool, createdAt string, updatedAt string) *License {
	this := License{}
	this.Id = id
	this.Key = key
	this.Status = status
	this.BusinessId = businessId
	this.ProductId = productId
	this.PaymentId = paymentId
	this.CustomerId = customerId
	this.ActivationLimit = activationLimit
	this.ActivationMessage = activationMessage
	this.InstancesCount = instancesCount
	this.ExpiryHours = expiryHours
	this.ExpiresAt = expiresAt
	this.Filters = filters
	this.Archived = archived
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewLicenseWithDefaults instantiates a new License object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseWithDefaults() *License {
	this := License{}
	return &this
}

// GetId returns the Id field value
func (o *License) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *License) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *License) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *License) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *License) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *License) SetKey(v string) {
	o.Key = v
}

// GetStatus returns the Status field value
func (o *License) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *License) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *License) SetStatus(v string) {
	o.Status = v
}

// GetBusinessId returns the BusinessId field value
func (o *License) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *License) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *License) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetProductId returns the ProductId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *License) GetProductId() string {
	if o == nil || o.ProductId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProductId.Get()
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductId.Get(), o.ProductId.IsSet()
}

// SetProductId sets field value
func (o *License) SetProductId(v string) {
	o.ProductId.Set(&v)
}

// GetPaymentId returns the PaymentId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *License) GetPaymentId() string {
	if o == nil || o.PaymentId.Get() == nil {
		var ret string
		return ret
	}

	return *o.PaymentId.Get()
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentId.Get(), o.PaymentId.IsSet()
}

// SetPaymentId sets field value
func (o *License) SetPaymentId(v string) {
	o.PaymentId.Set(&v)
}

// GetCustomerId returns the CustomerId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *License) GetCustomerId() string {
	if o == nil || o.CustomerId.Get() == nil {
		var ret string
		return ret
	}

	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// SetCustomerId sets field value
func (o *License) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}

// GetActivationLimit returns the ActivationLimit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *License) GetActivationLimit() float32 {
	if o == nil || o.ActivationLimit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ActivationLimit.Get()
}

// GetActivationLimitOk returns a tuple with the ActivationLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetActivationLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActivationLimit.Get(), o.ActivationLimit.IsSet()
}

// SetActivationLimit sets field value
func (o *License) SetActivationLimit(v float32) {
	o.ActivationLimit.Set(&v)
}

// GetActivationMessage returns the ActivationMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *License) GetActivationMessage() string {
	if o == nil || o.ActivationMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.ActivationMessage.Get()
}

// GetActivationMessageOk returns a tuple with the ActivationMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetActivationMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActivationMessage.Get(), o.ActivationMessage.IsSet()
}

// SetActivationMessage sets field value
func (o *License) SetActivationMessage(v string) {
	o.ActivationMessage.Set(&v)
}

// GetInstancesCount returns the InstancesCount field value
func (o *License) GetInstancesCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.InstancesCount
}

// GetInstancesCountOk returns a tuple with the InstancesCount field value
// and a boolean to check if the value has been set.
func (o *License) GetInstancesCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstancesCount, true
}

// SetInstancesCount sets field value
func (o *License) SetInstancesCount(v float32) {
	o.InstancesCount = v
}

// GetExpiryHours returns the ExpiryHours field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *License) GetExpiryHours() float32 {
	if o == nil || o.ExpiryHours.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ExpiryHours.Get()
}

// GetExpiryHoursOk returns a tuple with the ExpiryHours field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetExpiryHoursOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiryHours.Get(), o.ExpiryHours.IsSet()
}

// SetExpiryHours sets field value
func (o *License) SetExpiryHours(v float32) {
	o.ExpiryHours.Set(&v)
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *License) GetExpiresAt() string {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *License) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// GetFilters returns the Filters field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *License) GetFilters() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *License) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// SetFilters sets field value
func (o *License) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetArchived returns the Archived field value
func (o *License) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *License) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *License) SetArchived(v bool) {
	o.Archived = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *License) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *License) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *License) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *License) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *License) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *License) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o License) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o License) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["status"] = o.Status
	toSerialize["businessId"] = o.BusinessId
	toSerialize["productId"] = o.ProductId.Get()
	toSerialize["paymentId"] = o.PaymentId.Get()
	toSerialize["customerId"] = o.CustomerId.Get()
	toSerialize["activationLimit"] = o.ActivationLimit.Get()
	toSerialize["activationMessage"] = o.ActivationMessage.Get()
	toSerialize["instancesCount"] = o.InstancesCount
	toSerialize["expiryHours"] = o.ExpiryHours.Get()
	toSerialize["expiresAt"] = o.ExpiresAt.Get()
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["archived"] = o.Archived
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *License) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"status",
		"businessId",
		"productId",
		"paymentId",
		"customerId",
		"activationLimit",
		"activationMessage",
		"instancesCount",
		"expiryHours",
		"expiresAt",
		"filters",
		"archived",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLicense := _License{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLicense)

	if err != nil {
		return err
	}

	*o = License(varLicense)

	return err
}

type NullableLicense struct {
	value *License
	isSet bool
}

func (v NullableLicense) Get() *License {
	return v.value
}

func (v *NullableLicense) Set(val *License) {
	v.value = val
	v.isSet = true
}

func (v NullableLicense) IsSet() bool {
	return v.isSet
}

func (v *NullableLicense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicense(val *License) *NullableLicense {
	return &NullableLicense{value: val, isSet: true}
}

func (v NullableLicense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


