/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
)

// checks if the WebhookDisputePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDisputePayload{}

// WebhookDisputePayload struct for WebhookDisputePayload
type WebhookDisputePayload struct {
	// Internal dispute ID.
	Id *string `json:"id,omitempty"`
	PaymentId *string `json:"paymentId,omitempty"`
	// Dollar value, 2 d.p.
	Amount *string `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Status *string `json:"status,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	Editable *bool `json:"editable,omitempty"`
	NeedsResponseBy NullableTime `json:"needsResponseBy,omitempty"`
	CustomerName NullableString `json:"customerName,omitempty"`
	CustomerEmail NullableString `json:"customerEmail,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewWebhookDisputePayload instantiates a new WebhookDisputePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDisputePayload() *WebhookDisputePayload {
	this := WebhookDisputePayload{}
	return &this
}

// NewWebhookDisputePayloadWithDefaults instantiates a new WebhookDisputePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDisputePayloadWithDefaults() *WebhookDisputePayload {
	this := WebhookDisputePayload{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebhookDisputePayload) SetId(v string) {
	o.Id = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId) {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetPaymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *WebhookDisputePayload) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *WebhookDisputePayload) SetAmount(v string) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *WebhookDisputePayload) SetCurrency(v string) {
	o.Currency = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WebhookDisputePayload) SetStatus(v string) {
	o.Status = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookDisputePayload) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookDisputePayload) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *WebhookDisputePayload) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *WebhookDisputePayload) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *WebhookDisputePayload) UnsetReason() {
	o.Reason.Unset()
}

// GetEditable returns the Editable field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetEditable() bool {
	if o == nil || IsNil(o.Editable) {
		var ret bool
		return ret
	}
	return *o.Editable
}

// GetEditableOk returns a tuple with the Editable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.Editable) {
		return nil, false
	}
	return o.Editable, true
}

// HasEditable returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasEditable() bool {
	if o != nil && !IsNil(o.Editable) {
		return true
	}

	return false
}

// SetEditable gets a reference to the given bool and assigns it to the Editable field.
func (o *WebhookDisputePayload) SetEditable(v bool) {
	o.Editable = &v
}

// GetNeedsResponseBy returns the NeedsResponseBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookDisputePayload) GetNeedsResponseBy() time.Time {
	if o == nil || IsNil(o.NeedsResponseBy.Get()) {
		var ret time.Time
		return ret
	}
	return *o.NeedsResponseBy.Get()
}

// GetNeedsResponseByOk returns a tuple with the NeedsResponseBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookDisputePayload) GetNeedsResponseByOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NeedsResponseBy.Get(), o.NeedsResponseBy.IsSet()
}

// HasNeedsResponseBy returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasNeedsResponseBy() bool {
	if o != nil && o.NeedsResponseBy.IsSet() {
		return true
	}

	return false
}

// SetNeedsResponseBy gets a reference to the given NullableTime and assigns it to the NeedsResponseBy field.
func (o *WebhookDisputePayload) SetNeedsResponseBy(v time.Time) {
	o.NeedsResponseBy.Set(&v)
}
// SetNeedsResponseByNil sets the value for NeedsResponseBy to be an explicit nil
func (o *WebhookDisputePayload) SetNeedsResponseByNil() {
	o.NeedsResponseBy.Set(nil)
}

// UnsetNeedsResponseBy ensures that no value is present for NeedsResponseBy, not even an explicit nil
func (o *WebhookDisputePayload) UnsetNeedsResponseBy() {
	o.NeedsResponseBy.Unset()
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookDisputePayload) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerName.Get()
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookDisputePayload) GetCustomerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerName.Get(), o.CustomerName.IsSet()
}

// HasCustomerName returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasCustomerName() bool {
	if o != nil && o.CustomerName.IsSet() {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given NullableString and assigns it to the CustomerName field.
func (o *WebhookDisputePayload) SetCustomerName(v string) {
	o.CustomerName.Set(&v)
}
// SetCustomerNameNil sets the value for CustomerName to be an explicit nil
func (o *WebhookDisputePayload) SetCustomerNameNil() {
	o.CustomerName.Set(nil)
}

// UnsetCustomerName ensures that no value is present for CustomerName, not even an explicit nil
func (o *WebhookDisputePayload) UnsetCustomerName() {
	o.CustomerName.Unset()
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookDisputePayload) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerEmail.Get()
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookDisputePayload) GetCustomerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerEmail.Get(), o.CustomerEmail.IsSet()
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasCustomerEmail() bool {
	if o != nil && o.CustomerEmail.IsSet() {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given NullableString and assigns it to the CustomerEmail field.
func (o *WebhookDisputePayload) SetCustomerEmail(v string) {
	o.CustomerEmail.Set(&v)
}
// SetCustomerEmailNil sets the value for CustomerEmail to be an explicit nil
func (o *WebhookDisputePayload) SetCustomerEmailNil() {
	o.CustomerEmail.Set(nil)
}

// UnsetCustomerEmail ensures that no value is present for CustomerEmail, not even an explicit nil
func (o *WebhookDisputePayload) UnsetCustomerEmail() {
	o.CustomerEmail.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookDisputePayload) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookDisputePayload) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *WebhookDisputePayload) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *WebhookDisputePayload) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *WebhookDisputePayload) UnsetNotes() {
	o.Notes.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WebhookDisputePayload) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WebhookDisputePayload) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDisputePayload) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WebhookDisputePayload) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WebhookDisputePayload) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o WebhookDisputePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDisputePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PaymentId) {
		toSerialize["paymentId"] = o.PaymentId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if !IsNil(o.Editable) {
		toSerialize["editable"] = o.Editable
	}
	if o.NeedsResponseBy.IsSet() {
		toSerialize["needsResponseBy"] = o.NeedsResponseBy.Get()
	}
	if o.CustomerName.IsSet() {
		toSerialize["customerName"] = o.CustomerName.Get()
	}
	if o.CustomerEmail.IsSet() {
		toSerialize["customerEmail"] = o.CustomerEmail.Get()
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableWebhookDisputePayload struct {
	value *WebhookDisputePayload
	isSet bool
}

func (v NullableWebhookDisputePayload) Get() *WebhookDisputePayload {
	return v.value
}

func (v *NullableWebhookDisputePayload) Set(val *WebhookDisputePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDisputePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDisputePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDisputePayload(val *WebhookDisputePayload) *NullableWebhookDisputePayload {
	return &NullableWebhookDisputePayload{value: val, isSet: true}
}

func (v NullableWebhookDisputePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDisputePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


