/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutMethodList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutMethodList{}

// PayoutMethodList struct for PayoutMethodList
type PayoutMethodList struct {
	// List of payout methods available for the business
	Data []PayoutMethod `json:"data"`
}

type _PayoutMethodList PayoutMethodList

// NewPayoutMethodList instantiates a new PayoutMethodList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutMethodList(data []PayoutMethod) *PayoutMethodList {
	this := PayoutMethodList{}
	this.Data = data
	return &this
}

// NewPayoutMethodListWithDefaults instantiates a new PayoutMethodList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutMethodListWithDefaults() *PayoutMethodList {
	this := PayoutMethodList{}
	return &this
}

// GetData returns the Data field value
func (o *PayoutMethodList) GetData() []PayoutMethod {
	if o == nil {
		var ret []PayoutMethod
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PayoutMethodList) GetDataOk() ([]PayoutMethod, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PayoutMethodList) SetData(v []PayoutMethod) {
	o.Data = v
}

func (o PayoutMethodList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutMethodList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PayoutMethodList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutMethodList := _PayoutMethodList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutMethodList)

	if err != nil {
		return err
	}

	*o = PayoutMethodList(varPayoutMethodList)

	return err
}

type NullablePayoutMethodList struct {
	value *PayoutMethodList
	isSet bool
}

func (v NullablePayoutMethodList) Get() *PayoutMethodList {
	return v.value
}

func (v *NullablePayoutMethodList) Set(val *PayoutMethodList) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutMethodList) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutMethodList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutMethodList(val *PayoutMethodList) *NullablePayoutMethodList {
	return &NullablePayoutMethodList{value: val, isSet: true}
}

func (v NullablePayoutMethodList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutMethodList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


