/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncLoginDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncLoginDto{}

// SyncLoginDto struct for SyncLoginDto
type SyncLoginDto struct {
	// The JWT access token from the Live API server
	LiveToken string `json:"liveToken"`
}

type _SyncLoginDto SyncLoginDto

// NewSyncLoginDto instantiates a new SyncLoginDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncLoginDto(liveToken string) *SyncLoginDto {
	this := SyncLoginDto{}
	this.LiveToken = liveToken
	return &this
}

// NewSyncLoginDtoWithDefaults instantiates a new SyncLoginDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncLoginDtoWithDefaults() *SyncLoginDto {
	this := SyncLoginDto{}
	return &this
}

// GetLiveToken returns the LiveToken field value
func (o *SyncLoginDto) GetLiveToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiveToken
}

// GetLiveTokenOk returns a tuple with the LiveToken field value
// and a boolean to check if the value has been set.
func (o *SyncLoginDto) GetLiveTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiveToken, true
}

// SetLiveToken sets field value
func (o *SyncLoginDto) SetLiveToken(v string) {
	o.LiveToken = v
}

func (o SyncLoginDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncLoginDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["liveToken"] = o.LiveToken
	return toSerialize, nil
}

func (o *SyncLoginDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"liveToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncLoginDto := _SyncLoginDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncLoginDto)

	if err != nil {
		return err
	}

	*o = SyncLoginDto(varSyncLoginDto)

	return err
}

type NullableSyncLoginDto struct {
	value *SyncLoginDto
	isSet bool
}

func (v NullableSyncLoginDto) Get() *SyncLoginDto {
	return v.value
}

func (v *NullableSyncLoginDto) Set(val *SyncLoginDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncLoginDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncLoginDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncLoginDto(val *SyncLoginDto) *NullableSyncLoginDto {
	return &NullableSyncLoginDto{value: val, isSet: true}
}

func (v NullableSyncLoginDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncLoginDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


