/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LicensesActivateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LicensesActivateRequest{}

// LicensesActivateRequest struct for LicensesActivateRequest
type LicensesActivateRequest struct {
	// The license key.
	Key string `json:"key"`
	// Unique identifier of the device/machine being activated.
	DeviceIdentifier string `json:"deviceIdentifier"`
	// A user-friendly label/name for the instance.
	Name string `json:"name"`
}

type _LicensesActivateRequest LicensesActivateRequest

// NewLicensesActivateRequest instantiates a new LicensesActivateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicensesActivateRequest(key string, deviceIdentifier string, name string) *LicensesActivateRequest {
	this := LicensesActivateRequest{}
	this.Key = key
	this.DeviceIdentifier = deviceIdentifier
	this.Name = name
	return &this
}

// NewLicensesActivateRequestWithDefaults instantiates a new LicensesActivateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicensesActivateRequestWithDefaults() *LicensesActivateRequest {
	this := LicensesActivateRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *LicensesActivateRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *LicensesActivateRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *LicensesActivateRequest) SetKey(v string) {
	o.Key = v
}

// GetDeviceIdentifier returns the DeviceIdentifier field value
func (o *LicensesActivateRequest) GetDeviceIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceIdentifier
}

// GetDeviceIdentifierOk returns a tuple with the DeviceIdentifier field value
// and a boolean to check if the value has been set.
func (o *LicensesActivateRequest) GetDeviceIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceIdentifier, true
}

// SetDeviceIdentifier sets field value
func (o *LicensesActivateRequest) SetDeviceIdentifier(v string) {
	o.DeviceIdentifier = v
}

// GetName returns the Name field value
func (o *LicensesActivateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LicensesActivateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LicensesActivateRequest) SetName(v string) {
	o.Name = v
}

func (o LicensesActivateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LicensesActivateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["deviceIdentifier"] = o.DeviceIdentifier
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *LicensesActivateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"deviceIdentifier",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLicensesActivateRequest := _LicensesActivateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLicensesActivateRequest)

	if err != nil {
		return err
	}

	*o = LicensesActivateRequest(varLicensesActivateRequest)

	return err
}

type NullableLicensesActivateRequest struct {
	value *LicensesActivateRequest
	isSet bool
}

func (v NullableLicensesActivateRequest) Get() *LicensesActivateRequest {
	return v.value
}

func (v *NullableLicensesActivateRequest) Set(val *LicensesActivateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLicensesActivateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLicensesActivateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicensesActivateRequest(val *LicensesActivateRequest) *NullableLicensesActivateRequest {
	return &NullableLicensesActivateRequest{value: val, isSet: true}
}

func (v NullableLicensesActivateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicensesActivateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


