/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GithubReposResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubReposResponseDto{}

// GithubReposResponseDto struct for GithubReposResponseDto
type GithubReposResponseDto struct {
	// The GitHub repository ID
	Id float32 `json:"id"`
	// The repository full name (owner/repo)
	FullName string `json:"fullName"`
	// The repository name
	Name string `json:"name"`
}

type _GithubReposResponseDto GithubReposResponseDto

// NewGithubReposResponseDto instantiates a new GithubReposResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubReposResponseDto(id float32, fullName string, name string) *GithubReposResponseDto {
	this := GithubReposResponseDto{}
	this.Id = id
	this.FullName = fullName
	this.Name = name
	return &this
}

// NewGithubReposResponseDtoWithDefaults instantiates a new GithubReposResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubReposResponseDtoWithDefaults() *GithubReposResponseDto {
	this := GithubReposResponseDto{}
	return &this
}

// GetId returns the Id field value
func (o *GithubReposResponseDto) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GithubReposResponseDto) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GithubReposResponseDto) SetId(v float32) {
	o.Id = v
}

// GetFullName returns the FullName field value
func (o *GithubReposResponseDto) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *GithubReposResponseDto) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *GithubReposResponseDto) SetFullName(v string) {
	o.FullName = v
}

// GetName returns the Name field value
func (o *GithubReposResponseDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GithubReposResponseDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GithubReposResponseDto) SetName(v string) {
	o.Name = v
}

func (o GithubReposResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubReposResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fullName"] = o.FullName
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *GithubReposResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fullName",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGithubReposResponseDto := _GithubReposResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGithubReposResponseDto)

	if err != nil {
		return err
	}

	*o = GithubReposResponseDto(varGithubReposResponseDto)

	return err
}

type NullableGithubReposResponseDto struct {
	value *GithubReposResponseDto
	isSet bool
}

func (v NullableGithubReposResponseDto) Get() *GithubReposResponseDto {
	return v.value
}

func (v *NullableGithubReposResponseDto) Set(val *GithubReposResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubReposResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubReposResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubReposResponseDto(val *GithubReposResponseDto) *NullableGithubReposResponseDto {
	return &NullableGithubReposResponseDto{value: val, isSet: true}
}

func (v NullableGithubReposResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubReposResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


