/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionUserDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionUserDto{}

// SubscriptionUserDto struct for SubscriptionUserDto
type SubscriptionUserDto struct {
	// The unique ID of the user
	Id string `json:"id"`
	// The username of the user
	Username string `json:"username"`
	// The full name of the user
	Name string `json:"name"`
	// The email address of the user
	Email string `json:"email"`
}

type _SubscriptionUserDto SubscriptionUserDto

// NewSubscriptionUserDto instantiates a new SubscriptionUserDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionUserDto(id string, username string, name string, email string) *SubscriptionUserDto {
	this := SubscriptionUserDto{}
	this.Id = id
	this.Username = username
	this.Name = name
	this.Email = email
	return &this
}

// NewSubscriptionUserDtoWithDefaults instantiates a new SubscriptionUserDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionUserDtoWithDefaults() *SubscriptionUserDto {
	this := SubscriptionUserDto{}
	return &this
}

// GetId returns the Id field value
func (o *SubscriptionUserDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubscriptionUserDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubscriptionUserDto) SetId(v string) {
	o.Id = v
}

// GetUsername returns the Username field value
func (o *SubscriptionUserDto) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SubscriptionUserDto) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SubscriptionUserDto) SetUsername(v string) {
	o.Username = v
}

// GetName returns the Name field value
func (o *SubscriptionUserDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubscriptionUserDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubscriptionUserDto) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *SubscriptionUserDto) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SubscriptionUserDto) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SubscriptionUserDto) SetEmail(v string) {
	o.Email = v
}

func (o SubscriptionUserDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionUserDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["username"] = o.Username
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *SubscriptionUserDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"username",
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionUserDto := _SubscriptionUserDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionUserDto)

	if err != nil {
		return err
	}

	*o = SubscriptionUserDto(varSubscriptionUserDto)

	return err
}

type NullableSubscriptionUserDto struct {
	value *SubscriptionUserDto
	isSet bool
}

func (v NullableSubscriptionUserDto) Get() *SubscriptionUserDto {
	return v.value
}

func (v *NullableSubscriptionUserDto) Set(val *SubscriptionUserDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionUserDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionUserDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionUserDto(val *SubscriptionUserDto) *NullableSubscriptionUserDto {
	return &NullableSubscriptionUserDto{value: val, isSet: true}
}

func (v NullableSubscriptionUserDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionUserDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


