/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeterIngestEventDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeterIngestEventDto{}

// MeterIngestEventDto struct for MeterIngestEventDto
type MeterIngestEventDto struct {
	// Unique usage event ID for idempotency.
	EventId string `json:"event_id"`
	// Unique customer ID associated with the event.
	CustomerId string `json:"customer_id"`
	// Event name that should match a meter eventName.
	EventName string `json:"event_name"`
	// Event quantity value.
	Value *float32 `json:"value,omitempty"`
	// Metadata attached to the usage event.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Timestamp of the event in ISO 8601 format.
	Timestamp *string `json:"timestamp,omitempty"`
}

type _MeterIngestEventDto MeterIngestEventDto

// NewMeterIngestEventDto instantiates a new MeterIngestEventDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeterIngestEventDto(eventId string, customerId string, eventName string) *MeterIngestEventDto {
	this := MeterIngestEventDto{}
	this.EventId = eventId
	this.CustomerId = customerId
	this.EventName = eventName
	var value float32 = 1
	this.Value = &value
	return &this
}

// NewMeterIngestEventDtoWithDefaults instantiates a new MeterIngestEventDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterIngestEventDtoWithDefaults() *MeterIngestEventDto {
	this := MeterIngestEventDto{}
	var value float32 = 1
	this.Value = &value
	return &this
}

// GetEventId returns the EventId field value
func (o *MeterIngestEventDto) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *MeterIngestEventDto) SetEventId(v string) {
	o.EventId = v
}

// GetCustomerId returns the CustomerId field value
func (o *MeterIngestEventDto) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *MeterIngestEventDto) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetEventName returns the EventName field value
func (o *MeterIngestEventDto) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *MeterIngestEventDto) SetEventName(v string) {
	o.EventName = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MeterIngestEventDto) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MeterIngestEventDto) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *MeterIngestEventDto) SetValue(v float32) {
	o.Value = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *MeterIngestEventDto) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *MeterIngestEventDto) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *MeterIngestEventDto) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *MeterIngestEventDto) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterIngestEventDto) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *MeterIngestEventDto) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *MeterIngestEventDto) SetTimestamp(v string) {
	o.Timestamp = &v
}

func (o MeterIngestEventDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeterIngestEventDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["event_name"] = o.EventName
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

func (o *MeterIngestEventDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"customer_id",
		"event_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeterIngestEventDto := _MeterIngestEventDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeterIngestEventDto)

	if err != nil {
		return err
	}

	*o = MeterIngestEventDto(varMeterIngestEventDto)

	return err
}

type NullableMeterIngestEventDto struct {
	value *MeterIngestEventDto
	isSet bool
}

func (v NullableMeterIngestEventDto) Get() *MeterIngestEventDto {
	return v.value
}

func (v *NullableMeterIngestEventDto) Set(val *MeterIngestEventDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMeterIngestEventDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMeterIngestEventDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeterIngestEventDto(val *MeterIngestEventDto) *NullableMeterIngestEventDto {
	return &NullableMeterIngestEventDto{value: val, isSet: true}
}

func (v NullableMeterIngestEventDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeterIngestEventDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


