/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationalWebhookEndpointSecretResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationalWebhookEndpointSecretResponseDto{}

// OperationalWebhookEndpointSecretResponseDto struct for OperationalWebhookEndpointSecretResponseDto
type OperationalWebhookEndpointSecretResponseDto struct {
	Key string `json:"key"`
}

type _OperationalWebhookEndpointSecretResponseDto OperationalWebhookEndpointSecretResponseDto

// NewOperationalWebhookEndpointSecretResponseDto instantiates a new OperationalWebhookEndpointSecretResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationalWebhookEndpointSecretResponseDto(key string) *OperationalWebhookEndpointSecretResponseDto {
	this := OperationalWebhookEndpointSecretResponseDto{}
	this.Key = key
	return &this
}

// NewOperationalWebhookEndpointSecretResponseDtoWithDefaults instantiates a new OperationalWebhookEndpointSecretResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationalWebhookEndpointSecretResponseDtoWithDefaults() *OperationalWebhookEndpointSecretResponseDto {
	this := OperationalWebhookEndpointSecretResponseDto{}
	return &this
}

// GetKey returns the Key field value
func (o *OperationalWebhookEndpointSecretResponseDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *OperationalWebhookEndpointSecretResponseDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *OperationalWebhookEndpointSecretResponseDto) SetKey(v string) {
	o.Key = v
}

func (o OperationalWebhookEndpointSecretResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationalWebhookEndpointSecretResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *OperationalWebhookEndpointSecretResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationalWebhookEndpointSecretResponseDto := _OperationalWebhookEndpointSecretResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationalWebhookEndpointSecretResponseDto)

	if err != nil {
		return err
	}

	*o = OperationalWebhookEndpointSecretResponseDto(varOperationalWebhookEndpointSecretResponseDto)

	return err
}

type NullableOperationalWebhookEndpointSecretResponseDto struct {
	value *OperationalWebhookEndpointSecretResponseDto
	isSet bool
}

func (v NullableOperationalWebhookEndpointSecretResponseDto) Get() *OperationalWebhookEndpointSecretResponseDto {
	return v.value
}

func (v *NullableOperationalWebhookEndpointSecretResponseDto) Set(val *OperationalWebhookEndpointSecretResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationalWebhookEndpointSecretResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationalWebhookEndpointSecretResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationalWebhookEndpointSecretResponseDto(val *OperationalWebhookEndpointSecretResponseDto) *NullableOperationalWebhookEndpointSecretResponseDto {
	return &NullableOperationalWebhookEndpointSecretResponseDto{value: val, isSet: true}
}

func (v NullableOperationalWebhookEndpointSecretResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationalWebhookEndpointSecretResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


