/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the UserSettingsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSettingsUpdate{}

// UserSettingsUpdate struct for UserSettingsUpdate
type UserSettingsUpdate struct {
	// The custom store subdomain
	Subdomain *string `json:"subdomain,omitempty"`
	// The store name shown to customers
	StoreName *string `json:"storeName,omitempty"`
	// JSON structure listing social/contact URLs
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty"`
	// SEO title tag of the store page
	PageTitle *string `json:"pageTitle,omitempty"`
	// SEO description meta tag
	SeoDescription *string `json:"seoDescription,omitempty"`
	// SEO preview image URL
	SeoImage *string `json:"seoImage,omitempty"`
	// Favicon image URL
	FaviconUrl *string `json:"faviconUrl,omitempty"`
	// Google Analytics 4 Property ID
	GoogleAnalyticsId *string `json:"googleAnalyticsId,omitempty"`
	// Google Tag Manager Container ID
	GoogleTagManagerId *string `json:"googleTagManagerId,omitempty"`
	// Facebook Meta Pixel ID
	MetaPixelId *string `json:"metaPixelId,omitempty"`
	// Company/Store logo image URL
	LogoUrl *string `json:"logoUrl,omitempty"`
	// Name of the business entity
	BusinessTitle *string `json:"businessTitle,omitempty"`
	// Credit card statement descriptor
	StatementDescriptor *string `json:"statementDescriptor,omitempty"`
	// Three-letter currency symbol
	DefaultCurrency *string `json:"defaultCurrency,omitempty"`
	// User contact email
	Email *string `json:"email,omitempty"`
	// User first name
	FirstName *string `json:"firstName,omitempty"`
	// User last name
	LastName *string `json:"lastName,omitempty"`
	// User profile avatar URL
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	// Minimum balance required for automatic payouts in cents
	PayoutThreshold *float32 `json:"payoutThreshold,omitempty"`
	// Send email notifications on successful payments
	NotifyOnSuccess *bool `json:"notifyOnSuccess,omitempty"`
	// Send license keys automatically via email
	SendLicenseKeyEmail *bool `json:"sendLicenseKeyEmail,omitempty"`
	// Send download links automatically via email
	SendDigitalFileEmail *bool `json:"sendDigitalFileEmail,omitempty"`
	// Send email notifications on subscription plan changes
	NotifyOnSubscriptionPlanChanged *bool `json:"notifyOnSubscriptionPlanChanged,omitempty"`
	// Send email notifications when subscription is set to cancel
	NotifyOnSubscriptionSetToCancel *bool `json:"notifyOnSubscriptionSetToCancel,omitempty"`
	// Send email notifications when subscription is cancelled
	NotifyOnSubscriptionCancelled *bool `json:"notifyOnSubscriptionCancelled,omitempty"`
	// Send email notifications when refund is successful
	NotifyOnRefundSuccessful *bool `json:"notifyOnRefundSuccessful,omitempty"`
	// Send email notifications when payment fails
	NotifyOnPaymentFailed *bool `json:"notifyOnPaymentFailed,omitempty"`
	// Send email notifications when subscription renewal fails
	NotifyOnSubscriptionRenewalFailed *bool `json:"notifyOnSubscriptionRenewalFailed,omitempty"`
	// Send email notifications when subscription trial is ending
	NotifyOnSubscriptionTrialEnding *bool `json:"notifyOnSubscriptionTrialEnding,omitempty"`
	// Send email notifications when subscription is paused
	NotifyOnSubscriptionPaused *bool `json:"notifyOnSubscriptionPaused,omitempty"`
}

// NewUserSettingsUpdate instantiates a new UserSettingsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSettingsUpdate() *UserSettingsUpdate {
	this := UserSettingsUpdate{}
	return &this
}

// NewUserSettingsUpdateWithDefaults instantiates a new UserSettingsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSettingsUpdateWithDefaults() *UserSettingsUpdate {
	this := UserSettingsUpdate{}
	return &this
}

// GetSubdomain returns the Subdomain field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSubdomain() string {
	if o == nil || IsNil(o.Subdomain) {
		var ret string
		return ret
	}
	return *o.Subdomain
}

// GetSubdomainOk returns a tuple with the Subdomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSubdomainOk() (*string, bool) {
	if o == nil || IsNil(o.Subdomain) {
		return nil, false
	}
	return o.Subdomain, true
}

// HasSubdomain returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSubdomain() bool {
	if o != nil && !IsNil(o.Subdomain) {
		return true
	}

	return false
}

// SetSubdomain gets a reference to the given string and assigns it to the Subdomain field.
func (o *UserSettingsUpdate) SetSubdomain(v string) {
	o.Subdomain = &v
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *UserSettingsUpdate) SetStoreName(v string) {
	o.StoreName = &v
}

// GetSocialLinks returns the SocialLinks field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSocialLinks() map[string]interface{} {
	if o == nil || IsNil(o.SocialLinks) {
		var ret map[string]interface{}
		return ret
	}
	return o.SocialLinks
}

// GetSocialLinksOk returns a tuple with the SocialLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSocialLinksOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SocialLinks) {
		return map[string]interface{}{}, false
	}
	return o.SocialLinks, true
}

// HasSocialLinks returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSocialLinks() bool {
	if o != nil && !IsNil(o.SocialLinks) {
		return true
	}

	return false
}

// SetSocialLinks gets a reference to the given map[string]interface{} and assigns it to the SocialLinks field.
func (o *UserSettingsUpdate) SetSocialLinks(v map[string]interface{}) {
	o.SocialLinks = v
}

// GetPageTitle returns the PageTitle field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetPageTitle() string {
	if o == nil || IsNil(o.PageTitle) {
		var ret string
		return ret
	}
	return *o.PageTitle
}

// GetPageTitleOk returns a tuple with the PageTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetPageTitleOk() (*string, bool) {
	if o == nil || IsNil(o.PageTitle) {
		return nil, false
	}
	return o.PageTitle, true
}

// HasPageTitle returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasPageTitle() bool {
	if o != nil && !IsNil(o.PageTitle) {
		return true
	}

	return false
}

// SetPageTitle gets a reference to the given string and assigns it to the PageTitle field.
func (o *UserSettingsUpdate) SetPageTitle(v string) {
	o.PageTitle = &v
}

// GetSeoDescription returns the SeoDescription field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSeoDescription() string {
	if o == nil || IsNil(o.SeoDescription) {
		var ret string
		return ret
	}
	return *o.SeoDescription
}

// GetSeoDescriptionOk returns a tuple with the SeoDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSeoDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.SeoDescription) {
		return nil, false
	}
	return o.SeoDescription, true
}

// HasSeoDescription returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSeoDescription() bool {
	if o != nil && !IsNil(o.SeoDescription) {
		return true
	}

	return false
}

// SetSeoDescription gets a reference to the given string and assigns it to the SeoDescription field.
func (o *UserSettingsUpdate) SetSeoDescription(v string) {
	o.SeoDescription = &v
}

// GetSeoImage returns the SeoImage field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSeoImage() string {
	if o == nil || IsNil(o.SeoImage) {
		var ret string
		return ret
	}
	return *o.SeoImage
}

// GetSeoImageOk returns a tuple with the SeoImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSeoImageOk() (*string, bool) {
	if o == nil || IsNil(o.SeoImage) {
		return nil, false
	}
	return o.SeoImage, true
}

// HasSeoImage returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSeoImage() bool {
	if o != nil && !IsNil(o.SeoImage) {
		return true
	}

	return false
}

// SetSeoImage gets a reference to the given string and assigns it to the SeoImage field.
func (o *UserSettingsUpdate) SetSeoImage(v string) {
	o.SeoImage = &v
}

// GetFaviconUrl returns the FaviconUrl field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetFaviconUrl() string {
	if o == nil || IsNil(o.FaviconUrl) {
		var ret string
		return ret
	}
	return *o.FaviconUrl
}

// GetFaviconUrlOk returns a tuple with the FaviconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetFaviconUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FaviconUrl) {
		return nil, false
	}
	return o.FaviconUrl, true
}

// HasFaviconUrl returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasFaviconUrl() bool {
	if o != nil && !IsNil(o.FaviconUrl) {
		return true
	}

	return false
}

// SetFaviconUrl gets a reference to the given string and assigns it to the FaviconUrl field.
func (o *UserSettingsUpdate) SetFaviconUrl(v string) {
	o.FaviconUrl = &v
}

// GetGoogleAnalyticsId returns the GoogleAnalyticsId field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetGoogleAnalyticsId() string {
	if o == nil || IsNil(o.GoogleAnalyticsId) {
		var ret string
		return ret
	}
	return *o.GoogleAnalyticsId
}

// GetGoogleAnalyticsIdOk returns a tuple with the GoogleAnalyticsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetGoogleAnalyticsIdOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleAnalyticsId) {
		return nil, false
	}
	return o.GoogleAnalyticsId, true
}

// HasGoogleAnalyticsId returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasGoogleAnalyticsId() bool {
	if o != nil && !IsNil(o.GoogleAnalyticsId) {
		return true
	}

	return false
}

// SetGoogleAnalyticsId gets a reference to the given string and assigns it to the GoogleAnalyticsId field.
func (o *UserSettingsUpdate) SetGoogleAnalyticsId(v string) {
	o.GoogleAnalyticsId = &v
}

// GetGoogleTagManagerId returns the GoogleTagManagerId field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetGoogleTagManagerId() string {
	if o == nil || IsNil(o.GoogleTagManagerId) {
		var ret string
		return ret
	}
	return *o.GoogleTagManagerId
}

// GetGoogleTagManagerIdOk returns a tuple with the GoogleTagManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetGoogleTagManagerIdOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleTagManagerId) {
		return nil, false
	}
	return o.GoogleTagManagerId, true
}

// HasGoogleTagManagerId returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasGoogleTagManagerId() bool {
	if o != nil && !IsNil(o.GoogleTagManagerId) {
		return true
	}

	return false
}

// SetGoogleTagManagerId gets a reference to the given string and assigns it to the GoogleTagManagerId field.
func (o *UserSettingsUpdate) SetGoogleTagManagerId(v string) {
	o.GoogleTagManagerId = &v
}

// GetMetaPixelId returns the MetaPixelId field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetMetaPixelId() string {
	if o == nil || IsNil(o.MetaPixelId) {
		var ret string
		return ret
	}
	return *o.MetaPixelId
}

// GetMetaPixelIdOk returns a tuple with the MetaPixelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetMetaPixelIdOk() (*string, bool) {
	if o == nil || IsNil(o.MetaPixelId) {
		return nil, false
	}
	return o.MetaPixelId, true
}

// HasMetaPixelId returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasMetaPixelId() bool {
	if o != nil && !IsNil(o.MetaPixelId) {
		return true
	}

	return false
}

// SetMetaPixelId gets a reference to the given string and assigns it to the MetaPixelId field.
func (o *UserSettingsUpdate) SetMetaPixelId(v string) {
	o.MetaPixelId = &v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *UserSettingsUpdate) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetBusinessTitle returns the BusinessTitle field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetBusinessTitle() string {
	if o == nil || IsNil(o.BusinessTitle) {
		var ret string
		return ret
	}
	return *o.BusinessTitle
}

// GetBusinessTitleOk returns a tuple with the BusinessTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetBusinessTitleOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessTitle) {
		return nil, false
	}
	return o.BusinessTitle, true
}

// HasBusinessTitle returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasBusinessTitle() bool {
	if o != nil && !IsNil(o.BusinessTitle) {
		return true
	}

	return false
}

// SetBusinessTitle gets a reference to the given string and assigns it to the BusinessTitle field.
func (o *UserSettingsUpdate) SetBusinessTitle(v string) {
	o.BusinessTitle = &v
}

// GetStatementDescriptor returns the StatementDescriptor field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetStatementDescriptor() string {
	if o == nil || IsNil(o.StatementDescriptor) {
		var ret string
		return ret
	}
	return *o.StatementDescriptor
}

// GetStatementDescriptorOk returns a tuple with the StatementDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetStatementDescriptorOk() (*string, bool) {
	if o == nil || IsNil(o.StatementDescriptor) {
		return nil, false
	}
	return o.StatementDescriptor, true
}

// HasStatementDescriptor returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasStatementDescriptor() bool {
	if o != nil && !IsNil(o.StatementDescriptor) {
		return true
	}

	return false
}

// SetStatementDescriptor gets a reference to the given string and assigns it to the StatementDescriptor field.
func (o *UserSettingsUpdate) SetStatementDescriptor(v string) {
	o.StatementDescriptor = &v
}

// GetDefaultCurrency returns the DefaultCurrency field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetDefaultCurrency() string {
	if o == nil || IsNil(o.DefaultCurrency) {
		var ret string
		return ret
	}
	return *o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetDefaultCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCurrency) {
		return nil, false
	}
	return o.DefaultCurrency, true
}

// HasDefaultCurrency returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasDefaultCurrency() bool {
	if o != nil && !IsNil(o.DefaultCurrency) {
		return true
	}

	return false
}

// SetDefaultCurrency gets a reference to the given string and assigns it to the DefaultCurrency field.
func (o *UserSettingsUpdate) SetDefaultCurrency(v string) {
	o.DefaultCurrency = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserSettingsUpdate) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserSettingsUpdate) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserSettingsUpdate) SetLastName(v string) {
	o.LastName = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *UserSettingsUpdate) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetPayoutThreshold returns the PayoutThreshold field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetPayoutThreshold() float32 {
	if o == nil || IsNil(o.PayoutThreshold) {
		var ret float32
		return ret
	}
	return *o.PayoutThreshold
}

// GetPayoutThresholdOk returns a tuple with the PayoutThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetPayoutThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.PayoutThreshold) {
		return nil, false
	}
	return o.PayoutThreshold, true
}

// HasPayoutThreshold returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasPayoutThreshold() bool {
	if o != nil && !IsNil(o.PayoutThreshold) {
		return true
	}

	return false
}

// SetPayoutThreshold gets a reference to the given float32 and assigns it to the PayoutThreshold field.
func (o *UserSettingsUpdate) SetPayoutThreshold(v float32) {
	o.PayoutThreshold = &v
}

// GetNotifyOnSuccess returns the NotifyOnSuccess field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSuccess() bool {
	if o == nil || IsNil(o.NotifyOnSuccess) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSuccess
}

// GetNotifyOnSuccessOk returns a tuple with the NotifyOnSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSuccess) {
		return nil, false
	}
	return o.NotifyOnSuccess, true
}

// HasNotifyOnSuccess returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSuccess() bool {
	if o != nil && !IsNil(o.NotifyOnSuccess) {
		return true
	}

	return false
}

// SetNotifyOnSuccess gets a reference to the given bool and assigns it to the NotifyOnSuccess field.
func (o *UserSettingsUpdate) SetNotifyOnSuccess(v bool) {
	o.NotifyOnSuccess = &v
}

// GetSendLicenseKeyEmail returns the SendLicenseKeyEmail field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSendLicenseKeyEmail() bool {
	if o == nil || IsNil(o.SendLicenseKeyEmail) {
		var ret bool
		return ret
	}
	return *o.SendLicenseKeyEmail
}

// GetSendLicenseKeyEmailOk returns a tuple with the SendLicenseKeyEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSendLicenseKeyEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendLicenseKeyEmail) {
		return nil, false
	}
	return o.SendLicenseKeyEmail, true
}

// HasSendLicenseKeyEmail returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSendLicenseKeyEmail() bool {
	if o != nil && !IsNil(o.SendLicenseKeyEmail) {
		return true
	}

	return false
}

// SetSendLicenseKeyEmail gets a reference to the given bool and assigns it to the SendLicenseKeyEmail field.
func (o *UserSettingsUpdate) SetSendLicenseKeyEmail(v bool) {
	o.SendLicenseKeyEmail = &v
}

// GetSendDigitalFileEmail returns the SendDigitalFileEmail field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetSendDigitalFileEmail() bool {
	if o == nil || IsNil(o.SendDigitalFileEmail) {
		var ret bool
		return ret
	}
	return *o.SendDigitalFileEmail
}

// GetSendDigitalFileEmailOk returns a tuple with the SendDigitalFileEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetSendDigitalFileEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendDigitalFileEmail) {
		return nil, false
	}
	return o.SendDigitalFileEmail, true
}

// HasSendDigitalFileEmail returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasSendDigitalFileEmail() bool {
	if o != nil && !IsNil(o.SendDigitalFileEmail) {
		return true
	}

	return false
}

// SetSendDigitalFileEmail gets a reference to the given bool and assigns it to the SendDigitalFileEmail field.
func (o *UserSettingsUpdate) SetSendDigitalFileEmail(v bool) {
	o.SendDigitalFileEmail = &v
}

// GetNotifyOnSubscriptionPlanChanged returns the NotifyOnSubscriptionPlanChanged field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionPlanChanged() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionPlanChanged) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionPlanChanged
}

// GetNotifyOnSubscriptionPlanChangedOk returns a tuple with the NotifyOnSubscriptionPlanChanged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionPlanChangedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionPlanChanged) {
		return nil, false
	}
	return o.NotifyOnSubscriptionPlanChanged, true
}

// HasNotifyOnSubscriptionPlanChanged returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionPlanChanged() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionPlanChanged) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionPlanChanged gets a reference to the given bool and assigns it to the NotifyOnSubscriptionPlanChanged field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionPlanChanged(v bool) {
	o.NotifyOnSubscriptionPlanChanged = &v
}

// GetNotifyOnSubscriptionSetToCancel returns the NotifyOnSubscriptionSetToCancel field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionSetToCancel() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionSetToCancel) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionSetToCancel
}

// GetNotifyOnSubscriptionSetToCancelOk returns a tuple with the NotifyOnSubscriptionSetToCancel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionSetToCancelOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionSetToCancel) {
		return nil, false
	}
	return o.NotifyOnSubscriptionSetToCancel, true
}

// HasNotifyOnSubscriptionSetToCancel returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionSetToCancel() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionSetToCancel) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionSetToCancel gets a reference to the given bool and assigns it to the NotifyOnSubscriptionSetToCancel field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionSetToCancel(v bool) {
	o.NotifyOnSubscriptionSetToCancel = &v
}

// GetNotifyOnSubscriptionCancelled returns the NotifyOnSubscriptionCancelled field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionCancelled() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionCancelled) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionCancelled
}

// GetNotifyOnSubscriptionCancelledOk returns a tuple with the NotifyOnSubscriptionCancelled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionCancelledOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionCancelled) {
		return nil, false
	}
	return o.NotifyOnSubscriptionCancelled, true
}

// HasNotifyOnSubscriptionCancelled returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionCancelled() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionCancelled) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionCancelled gets a reference to the given bool and assigns it to the NotifyOnSubscriptionCancelled field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionCancelled(v bool) {
	o.NotifyOnSubscriptionCancelled = &v
}

// GetNotifyOnRefundSuccessful returns the NotifyOnRefundSuccessful field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnRefundSuccessful() bool {
	if o == nil || IsNil(o.NotifyOnRefundSuccessful) {
		var ret bool
		return ret
	}
	return *o.NotifyOnRefundSuccessful
}

// GetNotifyOnRefundSuccessfulOk returns a tuple with the NotifyOnRefundSuccessful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnRefundSuccessfulOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnRefundSuccessful) {
		return nil, false
	}
	return o.NotifyOnRefundSuccessful, true
}

// HasNotifyOnRefundSuccessful returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnRefundSuccessful() bool {
	if o != nil && !IsNil(o.NotifyOnRefundSuccessful) {
		return true
	}

	return false
}

// SetNotifyOnRefundSuccessful gets a reference to the given bool and assigns it to the NotifyOnRefundSuccessful field.
func (o *UserSettingsUpdate) SetNotifyOnRefundSuccessful(v bool) {
	o.NotifyOnRefundSuccessful = &v
}

// GetNotifyOnPaymentFailed returns the NotifyOnPaymentFailed field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnPaymentFailed() bool {
	if o == nil || IsNil(o.NotifyOnPaymentFailed) {
		var ret bool
		return ret
	}
	return *o.NotifyOnPaymentFailed
}

// GetNotifyOnPaymentFailedOk returns a tuple with the NotifyOnPaymentFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnPaymentFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnPaymentFailed) {
		return nil, false
	}
	return o.NotifyOnPaymentFailed, true
}

// HasNotifyOnPaymentFailed returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnPaymentFailed() bool {
	if o != nil && !IsNil(o.NotifyOnPaymentFailed) {
		return true
	}

	return false
}

// SetNotifyOnPaymentFailed gets a reference to the given bool and assigns it to the NotifyOnPaymentFailed field.
func (o *UserSettingsUpdate) SetNotifyOnPaymentFailed(v bool) {
	o.NotifyOnPaymentFailed = &v
}

// GetNotifyOnSubscriptionRenewalFailed returns the NotifyOnSubscriptionRenewalFailed field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionRenewalFailed() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionRenewalFailed) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionRenewalFailed
}

// GetNotifyOnSubscriptionRenewalFailedOk returns a tuple with the NotifyOnSubscriptionRenewalFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionRenewalFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionRenewalFailed) {
		return nil, false
	}
	return o.NotifyOnSubscriptionRenewalFailed, true
}

// HasNotifyOnSubscriptionRenewalFailed returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionRenewalFailed() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionRenewalFailed) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionRenewalFailed gets a reference to the given bool and assigns it to the NotifyOnSubscriptionRenewalFailed field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionRenewalFailed(v bool) {
	o.NotifyOnSubscriptionRenewalFailed = &v
}

// GetNotifyOnSubscriptionTrialEnding returns the NotifyOnSubscriptionTrialEnding field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionTrialEnding() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionTrialEnding) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionTrialEnding
}

// GetNotifyOnSubscriptionTrialEndingOk returns a tuple with the NotifyOnSubscriptionTrialEnding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionTrialEndingOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionTrialEnding) {
		return nil, false
	}
	return o.NotifyOnSubscriptionTrialEnding, true
}

// HasNotifyOnSubscriptionTrialEnding returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionTrialEnding() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionTrialEnding) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionTrialEnding gets a reference to the given bool and assigns it to the NotifyOnSubscriptionTrialEnding field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionTrialEnding(v bool) {
	o.NotifyOnSubscriptionTrialEnding = &v
}

// GetNotifyOnSubscriptionPaused returns the NotifyOnSubscriptionPaused field value if set, zero value otherwise.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionPaused() bool {
	if o == nil || IsNil(o.NotifyOnSubscriptionPaused) {
		var ret bool
		return ret
	}
	return *o.NotifyOnSubscriptionPaused
}

// GetNotifyOnSubscriptionPausedOk returns a tuple with the NotifyOnSubscriptionPaused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsUpdate) GetNotifyOnSubscriptionPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyOnSubscriptionPaused) {
		return nil, false
	}
	return o.NotifyOnSubscriptionPaused, true
}

// HasNotifyOnSubscriptionPaused returns a boolean if a field has been set.
func (o *UserSettingsUpdate) HasNotifyOnSubscriptionPaused() bool {
	if o != nil && !IsNil(o.NotifyOnSubscriptionPaused) {
		return true
	}

	return false
}

// SetNotifyOnSubscriptionPaused gets a reference to the given bool and assigns it to the NotifyOnSubscriptionPaused field.
func (o *UserSettingsUpdate) SetNotifyOnSubscriptionPaused(v bool) {
	o.NotifyOnSubscriptionPaused = &v
}

func (o UserSettingsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSettingsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subdomain) {
		toSerialize["subdomain"] = o.Subdomain
	}
	if !IsNil(o.StoreName) {
		toSerialize["storeName"] = o.StoreName
	}
	if !IsNil(o.SocialLinks) {
		toSerialize["socialLinks"] = o.SocialLinks
	}
	if !IsNil(o.PageTitle) {
		toSerialize["pageTitle"] = o.PageTitle
	}
	if !IsNil(o.SeoDescription) {
		toSerialize["seoDescription"] = o.SeoDescription
	}
	if !IsNil(o.SeoImage) {
		toSerialize["seoImage"] = o.SeoImage
	}
	if !IsNil(o.FaviconUrl) {
		toSerialize["faviconUrl"] = o.FaviconUrl
	}
	if !IsNil(o.GoogleAnalyticsId) {
		toSerialize["googleAnalyticsId"] = o.GoogleAnalyticsId
	}
	if !IsNil(o.GoogleTagManagerId) {
		toSerialize["googleTagManagerId"] = o.GoogleTagManagerId
	}
	if !IsNil(o.MetaPixelId) {
		toSerialize["metaPixelId"] = o.MetaPixelId
	}
	if !IsNil(o.LogoUrl) {
		toSerialize["logoUrl"] = o.LogoUrl
	}
	if !IsNil(o.BusinessTitle) {
		toSerialize["businessTitle"] = o.BusinessTitle
	}
	if !IsNil(o.StatementDescriptor) {
		toSerialize["statementDescriptor"] = o.StatementDescriptor
	}
	if !IsNil(o.DefaultCurrency) {
		toSerialize["defaultCurrency"] = o.DefaultCurrency
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatarUrl"] = o.AvatarUrl
	}
	if !IsNil(o.PayoutThreshold) {
		toSerialize["payoutThreshold"] = o.PayoutThreshold
	}
	if !IsNil(o.NotifyOnSuccess) {
		toSerialize["notifyOnSuccess"] = o.NotifyOnSuccess
	}
	if !IsNil(o.SendLicenseKeyEmail) {
		toSerialize["sendLicenseKeyEmail"] = o.SendLicenseKeyEmail
	}
	if !IsNil(o.SendDigitalFileEmail) {
		toSerialize["sendDigitalFileEmail"] = o.SendDigitalFileEmail
	}
	if !IsNil(o.NotifyOnSubscriptionPlanChanged) {
		toSerialize["notifyOnSubscriptionPlanChanged"] = o.NotifyOnSubscriptionPlanChanged
	}
	if !IsNil(o.NotifyOnSubscriptionSetToCancel) {
		toSerialize["notifyOnSubscriptionSetToCancel"] = o.NotifyOnSubscriptionSetToCancel
	}
	if !IsNil(o.NotifyOnSubscriptionCancelled) {
		toSerialize["notifyOnSubscriptionCancelled"] = o.NotifyOnSubscriptionCancelled
	}
	if !IsNil(o.NotifyOnRefundSuccessful) {
		toSerialize["notifyOnRefundSuccessful"] = o.NotifyOnRefundSuccessful
	}
	if !IsNil(o.NotifyOnPaymentFailed) {
		toSerialize["notifyOnPaymentFailed"] = o.NotifyOnPaymentFailed
	}
	if !IsNil(o.NotifyOnSubscriptionRenewalFailed) {
		toSerialize["notifyOnSubscriptionRenewalFailed"] = o.NotifyOnSubscriptionRenewalFailed
	}
	if !IsNil(o.NotifyOnSubscriptionTrialEnding) {
		toSerialize["notifyOnSubscriptionTrialEnding"] = o.NotifyOnSubscriptionTrialEnding
	}
	if !IsNil(o.NotifyOnSubscriptionPaused) {
		toSerialize["notifyOnSubscriptionPaused"] = o.NotifyOnSubscriptionPaused
	}
	return toSerialize, nil
}

type NullableUserSettingsUpdate struct {
	value *UserSettingsUpdate
	isSet bool
}

func (v NullableUserSettingsUpdate) Get() *UserSettingsUpdate {
	return v.value
}

func (v *NullableUserSettingsUpdate) Set(val *UserSettingsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSettingsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSettingsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSettingsUpdate(val *UserSettingsUpdate) *NullableUserSettingsUpdate {
	return &NullableUserSettingsUpdate{value: val, isSet: true}
}

func (v NullableUserSettingsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSettingsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


