/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
)

// checks if the UpdateFramerTemplateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFramerTemplateDto{}

// UpdateFramerTemplateDto struct for UpdateFramerTemplateDto
type UpdateFramerTemplateDto struct {
	// The name of the Framer template.
	Name *string `json:"name,omitempty"`
	// The public Framer remix link.
	RemixLink *string `json:"remixLink,omitempty"`
	// A brief description of the template.
	Description *string `json:"description,omitempty"`
}

// NewUpdateFramerTemplateDto instantiates a new UpdateFramerTemplateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFramerTemplateDto() *UpdateFramerTemplateDto {
	this := UpdateFramerTemplateDto{}
	return &this
}

// NewUpdateFramerTemplateDtoWithDefaults instantiates a new UpdateFramerTemplateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFramerTemplateDtoWithDefaults() *UpdateFramerTemplateDto {
	this := UpdateFramerTemplateDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateFramerTemplateDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFramerTemplateDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateFramerTemplateDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateFramerTemplateDto) SetName(v string) {
	o.Name = &v
}

// GetRemixLink returns the RemixLink field value if set, zero value otherwise.
func (o *UpdateFramerTemplateDto) GetRemixLink() string {
	if o == nil || IsNil(o.RemixLink) {
		var ret string
		return ret
	}
	return *o.RemixLink
}

// GetRemixLinkOk returns a tuple with the RemixLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFramerTemplateDto) GetRemixLinkOk() (*string, bool) {
	if o == nil || IsNil(o.RemixLink) {
		return nil, false
	}
	return o.RemixLink, true
}

// HasRemixLink returns a boolean if a field has been set.
func (o *UpdateFramerTemplateDto) HasRemixLink() bool {
	if o != nil && !IsNil(o.RemixLink) {
		return true
	}

	return false
}

// SetRemixLink gets a reference to the given string and assigns it to the RemixLink field.
func (o *UpdateFramerTemplateDto) SetRemixLink(v string) {
	o.RemixLink = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateFramerTemplateDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFramerTemplateDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateFramerTemplateDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateFramerTemplateDto) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateFramerTemplateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFramerTemplateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RemixLink) {
		toSerialize["remixLink"] = o.RemixLink
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableUpdateFramerTemplateDto struct {
	value *UpdateFramerTemplateDto
	isSet bool
}

func (v NullableUpdateFramerTemplateDto) Get() *UpdateFramerTemplateDto {
	return v.value
}

func (v *NullableUpdateFramerTemplateDto) Set(val *UpdateFramerTemplateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFramerTemplateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFramerTemplateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFramerTemplateDto(val *UpdateFramerTemplateDto) *NullableUpdateFramerTemplateDto {
	return &NullableUpdateFramerTemplateDto{value: val, isSet: true}
}

func (v NullableUpdateFramerTemplateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFramerTemplateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


