/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCustomer{}

// OrderCustomer struct for OrderCustomer
type OrderCustomer struct {
	// The customer identifier.
	CustomerId string `json:"customer_id"`
	// The customer email address.
	Email string `json:"email"`
	// The customer name.
	Name string `json:"name"`
	// The customer username.
	Username *string `json:"username,omitempty"`
}

type _OrderCustomer OrderCustomer

// NewOrderCustomer instantiates a new OrderCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCustomer(customerId string, email string, name string) *OrderCustomer {
	this := OrderCustomer{}
	this.CustomerId = customerId
	this.Email = email
	this.Name = name
	return &this
}

// NewOrderCustomerWithDefaults instantiates a new OrderCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCustomerWithDefaults() *OrderCustomer {
	this := OrderCustomer{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *OrderCustomer) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *OrderCustomer) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *OrderCustomer) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetEmail returns the Email field value
func (o *OrderCustomer) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *OrderCustomer) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *OrderCustomer) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *OrderCustomer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrderCustomer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrderCustomer) SetName(v string) {
	o.Name = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *OrderCustomer) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCustomer) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *OrderCustomer) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *OrderCustomer) SetUsername(v string) {
	o.Username = &v
}

func (o OrderCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *OrderCustomer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
		"email",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderCustomer := _OrderCustomer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderCustomer)

	if err != nil {
		return err
	}

	*o = OrderCustomer(varOrderCustomer)

	return err
}

type NullableOrderCustomer struct {
	value *OrderCustomer
	isSet bool
}

func (v NullableOrderCustomer) Get() *OrderCustomer {
	return v.value
}

func (v *NullableOrderCustomer) Set(val *OrderCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCustomer(val *OrderCustomer) *NullableOrderCustomer {
	return &NullableOrderCustomer{value: val, isSet: true}
}

func (v NullableOrderCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


