/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BrandCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandCreate{}

// BrandCreate struct for BrandCreate
type BrandCreate struct {
	// Name of the brand
	Name string `json:"name"`
	// The website URL associated with the brand
	WebsiteUrl NullableString `json:"websiteUrl,omitempty"`
	// Support email address for customer service
	SupportEmail NullableString `json:"supportEmail,omitempty"`
	// Short description of the brand
	Description NullableString `json:"description,omitempty"`
	// Brand logo image URL
	LogoUrl NullableString `json:"logoUrl,omitempty"`
	// Credit card statement descriptor (Max 22 chars)
	StatementDescriptor NullableString `json:"statementDescriptor,omitempty"`
}

type _BrandCreate BrandCreate

// NewBrandCreate instantiates a new BrandCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandCreate(name string) *BrandCreate {
	this := BrandCreate{}
	this.Name = name
	return &this
}

// NewBrandCreateWithDefaults instantiates a new BrandCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandCreateWithDefaults() *BrandCreate {
	this := BrandCreate{}
	return &this
}

// GetName returns the Name field value
func (o *BrandCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BrandCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BrandCreate) SetName(v string) {
	o.Name = v
}

// GetWebsiteUrl returns the WebsiteUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandCreate) GetWebsiteUrl() string {
	if o == nil || IsNil(o.WebsiteUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebsiteUrl.Get()
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandCreate) GetWebsiteUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebsiteUrl.Get(), o.WebsiteUrl.IsSet()
}

// HasWebsiteUrl returns a boolean if a field has been set.
func (o *BrandCreate) HasWebsiteUrl() bool {
	if o != nil && o.WebsiteUrl.IsSet() {
		return true
	}

	return false
}

// SetWebsiteUrl gets a reference to the given NullableString and assigns it to the WebsiteUrl field.
func (o *BrandCreate) SetWebsiteUrl(v string) {
	o.WebsiteUrl.Set(&v)
}
// SetWebsiteUrlNil sets the value for WebsiteUrl to be an explicit nil
func (o *BrandCreate) SetWebsiteUrlNil() {
	o.WebsiteUrl.Set(nil)
}

// UnsetWebsiteUrl ensures that no value is present for WebsiteUrl, not even an explicit nil
func (o *BrandCreate) UnsetWebsiteUrl() {
	o.WebsiteUrl.Unset()
}

// GetSupportEmail returns the SupportEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandCreate) GetSupportEmail() string {
	if o == nil || IsNil(o.SupportEmail.Get()) {
		var ret string
		return ret
	}
	return *o.SupportEmail.Get()
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandCreate) GetSupportEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportEmail.Get(), o.SupportEmail.IsSet()
}

// HasSupportEmail returns a boolean if a field has been set.
func (o *BrandCreate) HasSupportEmail() bool {
	if o != nil && o.SupportEmail.IsSet() {
		return true
	}

	return false
}

// SetSupportEmail gets a reference to the given NullableString and assigns it to the SupportEmail field.
func (o *BrandCreate) SetSupportEmail(v string) {
	o.SupportEmail.Set(&v)
}
// SetSupportEmailNil sets the value for SupportEmail to be an explicit nil
func (o *BrandCreate) SetSupportEmailNil() {
	o.SupportEmail.Set(nil)
}

// UnsetSupportEmail ensures that no value is present for SupportEmail, not even an explicit nil
func (o *BrandCreate) UnsetSupportEmail() {
	o.SupportEmail.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandCreate) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandCreate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BrandCreate) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BrandCreate) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BrandCreate) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BrandCreate) UnsetDescription() {
	o.Description.Unset()
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandCreate) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LogoUrl.Get()
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandCreate) GetLogoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoUrl.Get(), o.LogoUrl.IsSet()
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *BrandCreate) HasLogoUrl() bool {
	if o != nil && o.LogoUrl.IsSet() {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given NullableString and assigns it to the LogoUrl field.
func (o *BrandCreate) SetLogoUrl(v string) {
	o.LogoUrl.Set(&v)
}
// SetLogoUrlNil sets the value for LogoUrl to be an explicit nil
func (o *BrandCreate) SetLogoUrlNil() {
	o.LogoUrl.Set(nil)
}

// UnsetLogoUrl ensures that no value is present for LogoUrl, not even an explicit nil
func (o *BrandCreate) UnsetLogoUrl() {
	o.LogoUrl.Unset()
}

// GetStatementDescriptor returns the StatementDescriptor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandCreate) GetStatementDescriptor() string {
	if o == nil || IsNil(o.StatementDescriptor.Get()) {
		var ret string
		return ret
	}
	return *o.StatementDescriptor.Get()
}

// GetStatementDescriptorOk returns a tuple with the StatementDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandCreate) GetStatementDescriptorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatementDescriptor.Get(), o.StatementDescriptor.IsSet()
}

// HasStatementDescriptor returns a boolean if a field has been set.
func (o *BrandCreate) HasStatementDescriptor() bool {
	if o != nil && o.StatementDescriptor.IsSet() {
		return true
	}

	return false
}

// SetStatementDescriptor gets a reference to the given NullableString and assigns it to the StatementDescriptor field.
func (o *BrandCreate) SetStatementDescriptor(v string) {
	o.StatementDescriptor.Set(&v)
}
// SetStatementDescriptorNil sets the value for StatementDescriptor to be an explicit nil
func (o *BrandCreate) SetStatementDescriptorNil() {
	o.StatementDescriptor.Set(nil)
}

// UnsetStatementDescriptor ensures that no value is present for StatementDescriptor, not even an explicit nil
func (o *BrandCreate) UnsetStatementDescriptor() {
	o.StatementDescriptor.Unset()
}

func (o BrandCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.WebsiteUrl.IsSet() {
		toSerialize["websiteUrl"] = o.WebsiteUrl.Get()
	}
	if o.SupportEmail.IsSet() {
		toSerialize["supportEmail"] = o.SupportEmail.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.LogoUrl.IsSet() {
		toSerialize["logoUrl"] = o.LogoUrl.Get()
	}
	if o.StatementDescriptor.IsSet() {
		toSerialize["statementDescriptor"] = o.StatementDescriptor.Get()
	}
	return toSerialize, nil
}

func (o *BrandCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrandCreate := _BrandCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBrandCreate)

	if err != nil {
		return err
	}

	*o = BrandCreate(varBrandCreate)

	return err
}

type NullableBrandCreate struct {
	value *BrandCreate
	isSet bool
}

func (v NullableBrandCreate) Get() *BrandCreate {
	return v.value
}

func (v *NullableBrandCreate) Set(val *BrandCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandCreate(val *BrandCreate) *NullableBrandCreate {
	return &NullableBrandCreate{value: val, isSet: true}
}

func (v NullableBrandCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


