/*
Solifyn API

Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solifyn

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookDeliveryResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryResponseDto{}

// WebhookDeliveryResponseDto struct for WebhookDeliveryResponseDto
type WebhookDeliveryResponseDto struct {
	Id string `json:"id"`
	EndpointId string `json:"endpointId"`
	Event string `json:"event"`
	Payload map[string]interface{} `json:"payload"`
	ResponseStatus map[string]interface{} `json:"responseStatus,omitempty"`
	ResponseBody map[string]interface{} `json:"responseBody,omitempty"`
	DurationMs map[string]interface{} `json:"durationMs,omitempty"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
}

type _WebhookDeliveryResponseDto WebhookDeliveryResponseDto

// NewWebhookDeliveryResponseDto instantiates a new WebhookDeliveryResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryResponseDto(id string, endpointId string, event string, payload map[string]interface{}, status string, createdAt time.Time) *WebhookDeliveryResponseDto {
	this := WebhookDeliveryResponseDto{}
	this.Id = id
	this.EndpointId = endpointId
	this.Event = event
	this.Payload = payload
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookDeliveryResponseDtoWithDefaults instantiates a new WebhookDeliveryResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryResponseDtoWithDefaults() *WebhookDeliveryResponseDto {
	this := WebhookDeliveryResponseDto{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookDeliveryResponseDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookDeliveryResponseDto) SetId(v string) {
	o.Id = v
}

// GetEndpointId returns the EndpointId field value
func (o *WebhookDeliveryResponseDto) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *WebhookDeliveryResponseDto) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetEvent returns the Event field value
func (o *WebhookDeliveryResponseDto) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebhookDeliveryResponseDto) SetEvent(v string) {
	o.Event = v
}

// GetPayload returns the Payload field value
func (o *WebhookDeliveryResponseDto) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *WebhookDeliveryResponseDto) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise.
func (o *WebhookDeliveryResponseDto) GetResponseStatus() map[string]interface{} {
	if o == nil || IsNil(o.ResponseStatus) {
		var ret map[string]interface{}
		return ret
	}
	return o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetResponseStatusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResponseStatus) {
		return map[string]interface{}{}, false
	}
	return o.ResponseStatus, true
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *WebhookDeliveryResponseDto) HasResponseStatus() bool {
	if o != nil && !IsNil(o.ResponseStatus) {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given map[string]interface{} and assigns it to the ResponseStatus field.
func (o *WebhookDeliveryResponseDto) SetResponseStatus(v map[string]interface{}) {
	o.ResponseStatus = v
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise.
func (o *WebhookDeliveryResponseDto) GetResponseBody() map[string]interface{} {
	if o == nil || IsNil(o.ResponseBody) {
		var ret map[string]interface{}
		return ret
	}
	return o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetResponseBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResponseBody) {
		return map[string]interface{}{}, false
	}
	return o.ResponseBody, true
}

// HasResponseBody returns a boolean if a field has been set.
func (o *WebhookDeliveryResponseDto) HasResponseBody() bool {
	if o != nil && !IsNil(o.ResponseBody) {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given map[string]interface{} and assigns it to the ResponseBody field.
func (o *WebhookDeliveryResponseDto) SetResponseBody(v map[string]interface{}) {
	o.ResponseBody = v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *WebhookDeliveryResponseDto) GetDurationMs() map[string]interface{} {
	if o == nil || IsNil(o.DurationMs) {
		var ret map[string]interface{}
		return ret
	}
	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetDurationMsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return map[string]interface{}{}, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *WebhookDeliveryResponseDto) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given map[string]interface{} and assigns it to the DurationMs field.
func (o *WebhookDeliveryResponseDto) SetDurationMs(v map[string]interface{}) {
	o.DurationMs = v
}

// GetStatus returns the Status field value
func (o *WebhookDeliveryResponseDto) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookDeliveryResponseDto) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookDeliveryResponseDto) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponseDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookDeliveryResponseDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o WebhookDeliveryResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["endpointId"] = o.EndpointId
	toSerialize["event"] = o.Event
	toSerialize["payload"] = o.Payload
	if !IsNil(o.ResponseStatus) {
		toSerialize["responseStatus"] = o.ResponseStatus
	}
	if !IsNil(o.ResponseBody) {
		toSerialize["responseBody"] = o.ResponseBody
	}
	if !IsNil(o.DurationMs) {
		toSerialize["durationMs"] = o.DurationMs
	}
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *WebhookDeliveryResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"endpointId",
		"event",
		"payload",
		"status",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookDeliveryResponseDto := _WebhookDeliveryResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookDeliveryResponseDto)

	if err != nil {
		return err
	}

	*o = WebhookDeliveryResponseDto(varWebhookDeliveryResponseDto)

	return err
}

type NullableWebhookDeliveryResponseDto struct {
	value *WebhookDeliveryResponseDto
	isSet bool
}

func (v NullableWebhookDeliveryResponseDto) Get() *WebhookDeliveryResponseDto {
	return v.value
}

func (v *NullableWebhookDeliveryResponseDto) Set(val *WebhookDeliveryResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryResponseDto(val *WebhookDeliveryResponseDto) *NullableWebhookDeliveryResponseDto {
	return &NullableWebhookDeliveryResponseDto{value: val, isSet: true}
}

func (v NullableWebhookDeliveryResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


